// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

//! Autogenerated; see se_config_gen.

/// Slot numbers for the SE.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum Slot {
    #[allow(dead_code)]
    None = 0,
    IoProtectionSecret = 1,
    PinStretch = 2,
    PinAttempt = 3,
    PinHash = 4,
    MatchCount = 5,
    LastGood = 7,
    AesEntropy = 8,
    FirmwareTimestamp = 9,
    Seed = 10,
    SecurityCheckPrivateKey = 11,
    KeycardAuthenticity = 12,
    SeedFingerprint = 14,
    FidoPrivateKey = 15,
}

impl Slot {
    /// Return the size of the slot in bytes.
    ///
    /// # Panics
    ///
    /// Panics if the slot number is invalid (not in range 1..=15).
    pub const fn size(self) -> usize {
        match self as u8 {
            1..=7 => 36,
            8 => 416,
            9..=15 => 72,
            _ => panic!("Invalid slot number"),
        }
    }
}

/// Bytes [16..84) of chip config area.
#[cfg(not(feature = "production"))]
pub const SE_CONFIG_1: [u8; 68] = [
    0xc0, 0x00, 0x51, 0x00, 0x00, 0x00, 0x8f, 0x80, 0x8f, 0x80, 0xaf, 0x80, 0x8f, 0x4a, 0x00, 0x44, 0x00,
    0x00, 0x00, 0x44, 0xc4, 0x4a, 0x00, 0x00, 0xc4, 0x00, 0x8f, 0x20, 0x8f, 0x80, 0x00, 0x00, 0x00, 0x4a,
    0x8f, 0x60, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Bytes [90..128) of chip config area.
#[cfg(not(feature = "production"))]
pub const SE_CONFIG_2: [u8; 38] = [
    0x02, 0x15, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x00, 0x7c, 0x00, 0xbc, 0x01, 0xbc, 0x01, 0xdc, 0x01, 0x9c,
    0x01, 0x3c, 0x00, 0x9c, 0x01, 0xdc, 0x01, 0x9c, 0x01, 0x9c, 0x01, 0xb3, 0x01, 0xbc, 0x01, 0x3c, 0x00,
    0x9c, 0x01, 0xb3, 0x01,
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Counter {
    LoginAttempt = 0,
    FactoryReset = 1,
}

/*
RevNum: 00006002  len=4
Chip type: atecc608a
AES_Enable = 0x1
I2C_Enable = 0x0
GPIO Mode = 0x0
GPIO Default = 0x0
GPIO Detect (vs authout) = 0x0
GPIO SignalKey/KeyId = 0xc
I2C_Address(sic) = 0xc0
CountMatchKey = 0x5
CounterMatch enable = 1
ChipMode = 0x0

     Slot[0] = 0x0000 = SlotConfig(ReadKey=0, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=0, WriteKey=0, WriteConfig=0)=0x0000
KeyConfig[0] = 0x3c00 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=1, ReqRandom=0, ReqAuth=0, AuthKey=0, PersistentDisable=0, RFU=0, X509id=0)=0x003c

     Slot[1] = 0x8f80 = SlotConfig(ReadKey=15, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=1, WriteKey=0, WriteConfig=8)=0x808f
KeyConfig[1] = 0x7c00 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=1, ReqRandom=1, ReqAuth=0, AuthKey=0, PersistentDisable=0, RFU=0, X509id=0)=0x007c

     Slot[2] = 0x8f80 = SlotConfig(ReadKey=15, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=1, WriteKey=0, WriteConfig=8)=0x808f
KeyConfig[2] = 0xbc01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=1, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x01bc

     Slot[3] = 0xaf80 = SlotConfig(ReadKey=15, NoMac=0, LimitedUse=1, EncryptRead=0, IsSecret=1, WriteKey=0, WriteConfig=8)=0x80af
KeyConfig[3] = 0xbc01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=1, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x01bc

     Slot[4] = 0x8f4a = SlotConfig(ReadKey=15, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=1, WriteKey=10, WriteConfig=4)=0x4a8f
KeyConfig[4] = 0xdc01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=0, ReqRandom=1, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x01dc

     Slot[5] = 0x0044 = SlotConfig(ReadKey=0, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=0, WriteKey=4, WriteConfig=4)=0x4400
KeyConfig[5] = 0x9c01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=0, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x019c

     Slot[6] = 0x0000 = SlotConfig(ReadKey=0, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=0, WriteKey=0, WriteConfig=0)=0x0000
KeyConfig[6] = 0x3c00 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=1, ReqRandom=0, ReqAuth=0, AuthKey=0, PersistentDisable=0, RFU=0, X509id=0)=0x003c

     Slot[7] = 0x0044 = SlotConfig(ReadKey=0, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=0, WriteKey=4, WriteConfig=4)=0x4400
KeyConfig[7] = 0x9c01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=0, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x019c

     Slot[8] = 0xc44a = SlotConfig(ReadKey=4, NoMac=0, LimitedUse=0, EncryptRead=1, IsSecret=1, WriteKey=10, WriteConfig=4)=0x4ac4
KeyConfig[8] = 0xdc01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=0, ReqRandom=1, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x01dc

     Slot[9] = 0x0000 = SlotConfig(ReadKey=0, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=0, WriteKey=0, WriteConfig=0)=0x0000
KeyConfig[9] = 0x9c01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=0, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x019c

     Slot[10] = 0xc400 = SlotConfig(ReadKey=4, NoMac=0, LimitedUse=0, EncryptRead=1, IsSecret=1, WriteKey=0, WriteConfig=0)=0x00c4
KeyConfig[10] = 0x9c01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=0, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x019c

     Slot[11] = 0x8f20 = SlotConfig(ReadKey=15, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=1, WriteKey=0, WriteConfig=2)=0x208f
KeyConfig[11] = 0xb301 = KeyConfig(Private=1, PubInfo=1, KeyType=4, Lockable=1, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x01b3

     Slot[12] = 0x8f80 = SlotConfig(ReadKey=15, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=1, WriteKey=0, WriteConfig=8)=0x808f
KeyConfig[12] = 0xbc01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=1, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x01bc

     Slot[13] = 0x0000 = SlotConfig(ReadKey=0, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=0, WriteKey=0, WriteConfig=0)=0x0000
KeyConfig[13] = 0x3c00 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=1, ReqRandom=0, ReqAuth=0, AuthKey=0, PersistentDisable=0, RFU=0, X509id=0)=0x003c

     Slot[14] = 0x004a = SlotConfig(ReadKey=0, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=0, WriteKey=10, WriteConfig=4)=0x4a00
KeyConfig[14] = 0x9c01 = KeyConfig(Private=0, PubInfo=0, KeyType=7, Lockable=0, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x019c

     Slot[15] = 0x8f60 = SlotConfig(ReadKey=15, NoMac=0, LimitedUse=0, EncryptRead=0, IsSecret=1, WriteKey=0, WriteConfig=6)=0x608f
KeyConfig[15] = 0xb301 = KeyConfig(Private=1, PubInfo=1, KeyType=4, Lockable=1, ReqRandom=0, ReqAuth=1, AuthKey=1, PersistentDisable=0, RFU=0, X509id=0)=0x01b3

Counter[0]: ffffffff00000000  len=8
Counter[1]: ffffffff00000000  len=8
UseLock = 0x0
VolatileKeyPermission = 0x0
SecureBoot: 0000  len=2
KldfvLoc = 0xf0
KdflvStr: 0000  len=2
UserExtra = 0x0
UserExtraAdd = 0x0
LockValue = 0x55
LockConfig = 0x55
SlotLocked: ffff  len=2
ChipOptions: 0215  len=2
ChipOptions = ChipOptions(POSTEnable=0, IOProtKeyEnable=1, KDFAESEnable=0, mustbezero=0, ECDHProt=1, KDFProt=1, IOProtKey=1)=0x1502
X509format: 00000000  len=4
*/
