// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

import { AuthView } from "../../authenticator-types.slint";
import { CallbackResult } from "@ui/theme.slint";
export { CallbackResult }

import { EditPageVersion } from "@ui/pages.slint";
export { EditPageVersion }

@rust-attr(route(path = "/edit?{auth}&{label-validation}&{result}&{version}"))
export struct EditProps {
    auth: AuthView,
    label-validation: string,
    result: CallbackResult,
    version: EditPageVersion,
}
