#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

commit_regex="^[^#]*[A-Z]+[0-9]*-[0-9]+"

if ! grep -iqE "$commit_regex" $1; then
    echo "=========================================================================================" >&2
    echo "Aborting commit. Your commit message must contain a Linear issue ID" >&2
    echo "Example: 'SFT-123: '                     (To commit anyway, use the --no-verify option)" >&2
    echo "=========================================================================================" >&2
    exit 1
fi
