// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { EditCaller } from "../../security-key-types.slint";
import { Palette } from "@ui/theme.slint";
import { Navigate } from "../../gen/navigate.slint";
import { Button, HeadingLg, TextMd, ShieldPage, ContentSection, ButtonSection, WrappedIcon } from "@ui/widgets.slint";
import { EditPageVersion } from "@ui/pages.slint";
import { AddProps } from "./props.slint";
import { TR2, TrId } from "../../gen/tr.slint";

export component AddPage inherits ShieldPage {
    in property <AddProps> props;
    property <bool> light-mode:true;

    ContentSection {
        HorizontalLayout {
            alignment: center;
            WrappedIcon {
                outer-icon: "jumbo-circle";
                inner-icon: "key";
            }
        }

        HeadingLg {
            vertical-stretch: 0;
            text: TR2.lookup(TrId.NewHeader);
            horizontal-alignment: center;
        }

        TextMd {
            text: TR2.lookup(TrId.NewSubheader);
            color: Palette.content-secondary;
            horizontal-alignment: center;
        }
    }

    ButtonSection {
        Button {
            icon: "";
            label: TR2.lookup(TrId.NewNewSecurityKey);
            importance: primary;
            clicked => {
                Navigate.edit({
                    caller: EditCaller.add,
                    key: {
                        label: "",
                        icon: "",
                        live: false,
                        color: 0,
                        index: 0,
                    },
                    version: EditPageVersion.add,
                }, { })
            }
        }
    }
}
