// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size, UISize} from "@ui/theme.slint";
import { RestoreFileBackupRestoringProps } from "props.slint";
import { Navigate } from "../../../../gen/navigate.slint";
import { HeadingMd, TextSm, TextMd, Icon, JumboIcon, Shield, Button, TimerCircularProgress } from "@ui/widgets.slint";
import { OnboardingBasePage } from "../../../../widgets/base-page.slint";
import { OnboardingCallbacks } from "../../../../onboarding-callbacks.slint";
import { TR2, TrId } from "../../../../gen/tr.slint";

export component RestoreFileBackupRestoringPage inherits OnboardingBasePage {
    in property <RestoreFileBackupRestoringProps> props;

    VerticalLayout {
        alignment: stretch;
        spacing: Size.sz10;
        padding-top: Size.sz16;
        padding-left: Size.sz6;
        padding-right: Size.sz6;
        padding-bottom: Size.sz10;

        HorizontalLayout {
            alignment: center;
            TimerCircularProgress {
                indeterminate: true;
            }
        }

        VerticalLayout {
            spacing: Size.sz3;
            HeadingMd {
                vertical-stretch: 0;
                text: TR2.lookup(TrId.RecoverFileBackupRestoringHeader);
                horizontal-alignment: center;
            }

            TextMd {
                text: TR2.lookup(TrId.RecoverFileBackupRestoringSubheader);
                horizontal-alignment: center;
            }
        }

        Rectangle { }

        HorizontalLayout {
            vertical-stretch: 0;
            alignment: center;
            Button {
                width: 424px;
                label: @tr("Next screen (Debug Mode)");
                importance: primary;
                clicked => {
                    Navigate.import-settings({ });
                }
            }
        }
    }
}
