# SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

[toolchain]
channel = "nightly-2025-09-11"
components = ["rustfmt", "clippy", "rustc", "rust-src"]
targets = []
profile = "minimal"
