# Example configuration file for secrets-gen2

[keys]
# P256 keypair for provisioning to sign messages sent to the SCS server to send the public key of each
# Passport Prime device as it is provisioned.
ProvisioningSigningKey = { type = "P256" }

# P256 keypair for SC server to sign challenges and response messages
ScsSigningKey = { type = "P256" }

# Random 32-byte key for FIDO to sign messages as being from Foundation
FidoPrivateKey = { type = "P256" }

# Random entropy for bootloader
# BootloaderEntropy = { type = "random", params = { length = 32, count = 1 } }

[injectors]
# Inject into provision.toml
[[injectors.files]]
file = "provisioning-test/provisioning-config.toml"
type = "toml"
injections = [
  { key = "ProvisioningSigningKey", format = "private-hex", name = "provisioning-secret" },
  { key = "ScsSigningKey", format = "public-compressed-hex", name = "sc-server-pubkey" },
  { key = "FidoPrivateKey", format = "private-hex" },
]

# Inject into .env file
[[injectors.files]]
file = "provisioning-test/scs.env"
type = "env"
injections = [
  { key = "ScsSigningKey", format = "private-hex", name = "SC_SIGNING_KEY" },
  { key = "ProvisioningSigningKey", format = "public-hex", name = "SC_PROVISIONING_PUBKEY" },
  # { key = "BootloaderEntropy", format = "csv", name = "SC_EXTRA_ENTROPY" },
]

# Save keys to individual files
[[injectors.files]]
file = "provisioning-test/generated-keys/provisioning-signing-private-key.pem"
type = "raw"
injections = [{ key = "ProvisioningSigningKey", format = "private-pem" }]

[[injectors.files]]
file = "provisioning-test/generated-keys/provisioning-signing-public-key.pem"
type = "raw"
injections = [{ key = "ProvisioningSigningKey", format = "public-pem" }]

[[injectors.files]]
file = "provisioning-test/generated-keys/scs-signing-private-key.pem"
type = "raw"
injections = [{ key = "ScsSigningKey", format = "private-pem" }]

[[injectors.files]]
file = "provisioning-test/generated-keys/scs-signing-public-key.pem"
type = "raw"
injections = [{ key = "ScsSigningKey", format = "public-pem" }]

[[injectors.files]]
file = "provisioning-test/generated-keys/fido-private-key.pem"
type = "raw"
injections = [{ key = "FidoPrivateKey", format = "private-pem" }]

[[injectors.files]]
file = "provisioning-test/generated-keys/fido-ec-private-key.pem"
type = "raw"
injections = [{ key = "FidoPrivateKey", format = "ec-private-pem" }]

[[injectors.files]]
file = "provisioning-test/generated-keys/fido-public-key.pem"
type = "raw"
injections = [{ key = "FidoPrivateKey", format = "public-pem" }]
