[servers."os/security"]
SetSeedAndPin = { id = 1, type = "archive" }
ChangePin = { id = 2, type = "archive" }
Login = { id = 3, type = "archive" }
GetAttemptsRemaining = { id = 4, type = "archive" }
GetFactoryResetCounter = { id = 5, type = "archive" }
GetSeed = { id = 6, type = "archive" }
SetSeed = { id = 7, type = "archive" }
GetAppSeed = { id = 8, type = "archive" }
GetFirmwareTimestamp = { id = 9, type = "archive" }
SetFirmwareTimestamp = { id = 10, type = "archive" }
Logout = { id = 11, type = "blockingScalar" }
LoggedIn = { id = 12, type = "blockingScalar" }
GetPin = { id = 13, type = "archive", cfg = "not(keyos)" }
Lockout = { id = 14, type = "archive" }
SignWithSecurityCheckKey = { id = 15, type = "archive" }
GetSecurityWords = { id = 16, type = "archive" }
SetAttempts = { id = 17, type = "archive", cfg = "not(keyos)" }
GetSeedFingerprint = { id = 18, type = "archive" }
ComputeSeedFingerprint = { id = 19, type = "archive" }
SignWithFidoKey = { id = 20, type = "archive" }
GetOsVersionInfo = { id = 21, type = "archive" }
ScChallenge = { id = 22, type = "archive" }
IsPinSet = { id = 23, type = "archive" }
GetDeviceId = { id = 24, type = "archive" }
KeycardAuthenticityMac = { id = 25, type = "archive" }
GetBluetoothChallengeSecret = { id = 26, type = "archive" }
SetBluetoothCheckSecretSent = { id = 27, type = "blockingScalar" }
SetBluetoothDeviceId = { id = 28, type = "archive" }
GetRandom = { id = 29, type = "archive" }
GetPinEntryMode = { id = 30, type = "archive" }
GetMasterKeyState = { id = 31, type = "blockingScalar" }
GetFidoPubkey = { id = 32, type = "archive" }
GetBootloaderBuildDate = { id = 33, type = "archive" }
