// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import {Palette, Importance, Size, Font, FontSize, Utils, ColorHelpers} from "@ui/theme.slint";

import {Icon} from "./icon.slint";
import {TextLg} from "./txt.slint";
import {TimerLoader} from "./loader.slint";

export component Button inherits Rectangle {
    // Override inherited properties
    background: bg-color;
    border-radius: Size.sz6;
    height: Size.sz15;
    clip: true;

    // Private properties
    private property <brush> text-color: ColorHelpers.get-btn-content-color(importance, touchArea.pressed || force-pressed, enabled);
    private property <brush> bg-color: ColorHelpers.get-btn-bg-color(importance, touchArea.pressed || force-pressed, enabled);

    // Public properties
    in property <string> id;
    in property <string> label: "Button";
    in property <brush> label-color: text-color;
    in property <Importance> importance;
    in property <bool> enabled: true;
    in property <string> icon;
    in property <bool> loading: false;
    in property <bool> force-pressed: false;

    // Callbacks
    callback clicked(string);

    HorizontalLayout {
        spacing: Size.sz2;
        alignment: center;
        padding-left: Size.sz6;
        padding-right: Size.sz6;

        if loading: VerticalLayout {
            alignment: center;
            TimerLoader {
                running: true;
                loader-color: label-color;
                active-color: label-color.darker(0.4);
            }
        }

        if !loading && icon != "": VerticalLayout {
            alignment: center;
            Icon {
                name: icon;
                horizontal-stretch: 1;
                color: label-color;
            }
        }
        if label != "": TextLg {
            horizontal-alignment: center;
            vertical-alignment: center;
            text: root.label;
            color: label-color;
            bold: true;
            horizontal-stretch: 0;
        }
    }

    touchArea := TouchArea {
        clicked => {
            if (enabled) {
                clicked(id);
            }
        }
    }
}
