// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import {Palette, Size, CurrentTheme} from "@ui/theme.slint";

import {Icon} from "./icon.slint";
import {TextLg} from "./txt.slint";
import {ScaledTouch} from "scaled-touch.slint";

// A text-only segmented selector - no animation
export component SegmentedControl inherits Rectangle {
    // Override inherited properties
    background: Palette.background-primary-alternative;
    border-radius: Size.sz13 / 2;
    height: Size.sz13;
    clip: true;

    // Public properties
    in property <string> id;
    in property <[string]> labels;
    in property <[string]> icons;
    in-out property <int> selected_index: 0;
    in property <bool> enabled: true;
    in property <float> touch-factor: 2;

    // Private properties
    private property <bool> is_pressed: false;
    private property <brush> bg_color: get-segment-bg-color(selected_index);

    // Callbacks
    callback changed(string, int);

    // Helper functions
    function get-segment-bg-color(index: int) -> brush {
        // Not selected
        if (selected_index != index) {
            return Palette.transparent;
        }

        // Disabled
        if (!enabled) {
            return Palette.background-info-subtle;
        }

        // Normal
        return Palette.background-brand;
    }

    function get-text-color(index: int) -> brush {
        if (selected_index == index) {
            return Palette.content-button;
        } else {
            return Palette.content-secondary;
        }
    }

    HorizontalLayout {
        padding: Size.sz1;

        for label[index] in labels: Rectangle {
            HorizontalLayout {
                VerticalLayout {
                    Rectangle {
                        width: 100%;
                        height: 100%;
                        background: get-segment-bg-color(index);
                        border-radius: Size.sz6;

                        VerticalLayout {
                            alignment: center;

                            HorizontalLayout {
                                alignment: center;
                                spacing: Size.sz2;

                                if (index < icons.length && icons[index] != ""): VerticalLayout {
                                    alignment: center;
                                    Icon {
                                        width: 24px;
                                        name: icons[index];
                                        color: get-text-color(index);
                                    }
                                }

                                TextLg {
                                    text: label;
                                    color: get-text-color(index);
                                    bold: true;
                                }
                            }
                        }
                    }
                }
            }

            scaled-touch := ScaledTouch {
                enabled: root.enabled;
                touch-factor: root.touch-factor;
                scale-horizontal: false;
                clicked => {
                    root.selected_index = index;
                    root.changed(id, index);
                }
                pointer-event(e) => {
                    if (e.kind == PointerEventKind.down) {
                        root.is_pressed = true;
                    } else if (e.kind == PointerEventKind.up) {
                        root.is_pressed = false;
                    }
                }
            }

            states [
                pressed when scaled-touch.pressed: {
                    background: selected_index == index ? Palette.background-brand-pressed : Palette.background-pressed;
                }
            ]
        }
    }
}
