// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size } from "../theme.slint";
import { TextMd } from "./txt.slint";
import { Icon } from "./icon.slint";

export component ShowHide inherits VerticalLayout {
    in property <string> text;

    property <bool> show: false;

    spacing: Size.zero;
    Rectangle {
        height: Size.sz14;
        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                spacing: Size.sz3;
                padding-left: Size.sz4;
                alignment: start;

                TextMd {
                    text: text;
                    color: Palette.content-link;
                    width: 207px;
                }

                Icon {
                    name: show ? "chevron-up" : "chevron-down";
                    horizontal-stretch: 1;
                    color: Palette.content-link;
                }
            }
        }

        touchArea := TouchArea {
            clicked => {
                show = !show;
            }
        }
    }

    Rectangle {
        visible: show;

        @children
    }
}
