// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Button, ButtonSection, Icon, JumboIcon, Shield, TimerCircularProgress, HeadingMd, WrappedIcon } from "@ui/widgets.slint";
import { OnboardingBasePage, OnboardingContentSection } from "../../widgets/base-page.slint";
import { Palette, Size, UISize, CardColor } from "@ui/theme.slint";
import { ConnectWalletProps } from "props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { AccountCard } from "@ui/widgets/account-card.slint";
import { OnboardingCallbacks } from "../../onboarding-callbacks.slint";
import { TR2, TrId } from "../../gen/tr.slint";
import { JumboIconPageBody } from "../../../../../ui/ui/widgets.slint";

export component ConnectWalletPage inherits OnboardingBasePage {
    in property <ConnectWalletProps> props;
    property <bool> wallet-connected: OnboardingCallbacks.wallet-connected;

    init => {
        OnboardingCallbacks.start-wallet-connect();
    }

    JumboIconPageBody {
        OnboardingContentSection {
            HorizontalLayout {
                alignment: center;
                if !wallet-connected: TimerCircularProgress {
                    indeterminate: true;
                }

                if wallet-connected: WrappedIcon {
                    outer-icon: "jumbo-circle";
                    inner-icon: "check";
                }
            }

            HeadingMd {
                horizontal-alignment: center;
                vertical-stretch: 0;
                text: wallet-connected ? TR2.lookup(TrId.ConnectionSuccessHeader) : TR2.lookup(TrId.ConnectionMainHeader);
            }

            Rectangle {
                vertical-stretch: 1;
            }

            if wallet-connected: AccountCard {
                name: OnboardingCallbacks.account-name;
                icon: "bitcoin";
                card-color: CardColor.light-copper;
            }
        }

        ButtonSection {
            Button {
                label: TR2.lookup(TrId.CommonButtonFinish);
                visible: wallet-connected;

                clicked => {
                    OnboardingCallbacks.finish-onboarding();
                }
            }
        }
    }
}
