// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Navigate } from "../../gen/navigate.slint";
import { OnboardingCallbacks } from "../../onboarding-callbacks.slint";
import { HeadingMd, Dialog, TextSm, TextMd, Button, ButtonSection, AppHeader, NavHeader } from "@ui/widgets.slint";
import { Palette, Size, UISize } from "@ui/theme.slint";
import { ShieldSection, ShieldContent, OnboardingShieldPage, OverlayImage } from "../../widgets/shield-page.slint";
import { TR2, TrId } from "../../gen/tr.slint";

component Overview inherits OnboardingShieldPage {
    callback show-confirmation();

    ShieldSection {
        ShieldContent {
            HeadingMd {
                vertical-stretch: 0;
                text: TR2.lookup(TrId.SeedIntroHeader);
                horizontal-alignment: center;
            }

            TextSm {
                text: TR2.lookup(TrId.SeedIntroContent);
                color: Palette.content-secondary;
                horizontal-alignment: center;
            }
        }

        ButtonSection {
            Button {
                label: TR2.lookup(TrId.SeedIntroRestore);
                importance: tertiary;
                clicked => {
                    Navigate.restore-seed({ });
                }
            }

            Button {
                label: TR2.lookup(TrId.SeedIntroCreateMasterKey);
                importance: primary;
                clicked => {
                    root.show-confirmation();
                }
            }
        }
    }

    OverlayImage {
        image: "images/three-d/master-key-separated";
    }
}

component Confirmation inherits OnboardingShieldPage {
    callback go-back();

    NavHeader {
        y: 0;
        clicked => {
            root.go-back();
        }
    }

    ShieldSection {
        ShieldContent {
            HeadingMd {
                vertical-stretch: 0;
                text: TR2.lookup(TrId.SeedMainHeader);
                horizontal-alignment: center;
            }

            TextSm {
                text: TR2.lookup(TrId.SeedMainContent);
                color: Palette.content-secondary;
                horizontal-alignment: center;
            }
        }

        ButtonSection {
            Button {
                label: TR2.lookup(TrId.CommonButtonContinue);
                importance: primary;
                clicked => {
                    Navigate.create-master-seed({ });
                }
            }
        }
    }

    OverlayImage {
        image: "images/three-d/master-key";
    }
}

export component MasterSeedPage inherits Rectangle {
    property <bool> show-confirmation: false;

    if !show-confirmation: Overview {
        show-confirmation => {
            root.show-confirmation = true;
        }
    }

    if show-confirmation: Confirmation {
        go-back => {
            root.show-confirmation = false;
        }
    }
}
