// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { MagicBackupProps } from "props.slint";
import { OnboardingBasePage } from "../../../widgets/base-page.slint";
import { Navigate } from "../../../gen/navigate.slint";
import { OnboardingCallbacks } from "../../../onboarding-callbacks.slint";
import { OnboardingShieldPage, ShieldContent, ShieldSection, OverlayImage } from "../../../widgets/shield-page.slint";
import { Size } from "@ui/theme.slint";
import { TR2, TrId } from "../../../gen/tr.slint";
import { HeadingMd, TextMd, ButtonSection, Button } from "@ui/widgets.slint";
import { Size } from "@ui/theme.slint";

export component MagicBackupPage inherits OnboardingShieldPage {
    in property <MagicBackupProps> props;

    property <bool> first-page: true;

    ShieldSection {
        ShieldContent {
            padding: Size.sz4;
            padding-top: Size.sz4; // Override internal top padding
            alignment: start;

            HeadingMd {
                text: TR2.lookup(TrId.KeycardBackupMagicCreateHeader);
                horizontal-alignment: center;
            }

            TextMd {
                text: first-page ? TR2.lookup(TrId.BackupMagicMain1Subheader) : TR2.lookup(TrId.KeycardBackupMagicCreateContent);
                horizontal-alignment: center;
            }
        }

        ButtonSection {
            Button {
                label: TR2.lookup(TrId.CommonButtonContinue);
                importance: primary;
                clicked => {
                    if (first-page) {
                        first-page = false;
                    } else {
                        Navigate.keycard-tip({ });
                    }
                }
            }
        }
    }

    OverlayImage {
        y: 15px;
        image: "images/three-d/magic-backup";
    }
}
