// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Router } from "./gen/router.slint";
import { Images, UISize, Utils, CurrentTheme } from "@ui/theme.slint";
import { SecurityKeyCallbacks } from "./security-key-callbacks.slint";
import { TR } from "@ui/i18n/i18n.slint";
import { BaseWindow } from "@ui/widgets.slint";

export component AppWindow inherits BaseWindow {
    Router { }
}

export * from "gen/exports.slint";
export { Utils, Images, TR, CurrentTheme }
export { SecurityKeyCallbacks }
