// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { CallbackResult } from "@ui/theme.slint";
import { KeyView, AuthenticatingState } from "./security-key-types.slint";
import { DropdownModel } from "@ui/widgets.slint";

export global SecurityKeyCallbacks {
    // callback scan-clicked() -> string;

    callback search(string);
    callback save(string, string, bool, int) -> CallbackResult;
    callback validate-new-label(string) -> string;
    callback validate-edit-label(int, string) -> string;
    callback edit(int, string, string, bool, int) -> CallbackResult;
    callback set-archived(int, bool);
    callback set-archive-mode(bool);
    callback move-position(int, bool);
    callback set-sort-mode(int);
    pure callback get-view-index([KeyView], int) -> int;
    pure callback get-dropdown-index([DropdownModel], int) -> int;
    callback user-presence-check(bool);
    callback dismiss-outcome();
    callback select-key(int);
    callback deselect-key();
    callback is-nfc-on() -> bool;
    pure callback is-usb-on() -> bool;

    in-out property <[KeyView]> entries;
    in-out property <int> sort-mode: 0;
    in-out property <AuthenticatingState> auth-state;
    in-out property <int> selected-index;
    in-out property <[DropdownModel]> dropdown-model;
    in-out property <bool> is-outcome-mode: false;
    in-out property <bool> show-no-keys-modal: false;
}

export { DropdownModel }
