// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size, UISize, Importance } from "@ui/theme.slint";

import { TextSm } from "./txt.slint";

export component Button inherits Rectangle {
    // Override inherited properties
    background: (enabled != invert-enabled-colors) ? bg-color : bg-color.mix(white, 0.5);
    border-radius: Size.sz2;
    height: Size.sz14;
    clip: true;
    padding-left: Size.sz1;
    padding-right: Size.sz1;

    // Private properties
    private property <brush> text-color: (importance == Importance.primary || importance == Importance.tertiary) ? Palette.content-primary-inverse : Palette.background-brand;
    private property <brush> bg-color: importance == Importance.primary ? Palette.background-brand : (importance == Importance.secondary ? Palette.background-primary : Palette.transparent);

    // Public properties
    in property <string> id;
    in property <string> label;
    in property <bool> invert-enabled-colors: false;
    in property <brush> label-color: (enabled != invert-enabled-colors) ? text-color : text-color.mix(white, 0.5);
    in property <Importance> importance;
    in property <bool> enabled: true;

    // Callbacks
    callback clicked(string);

    // TODO: Figure out how inheriting from Rectangle is different than using it as the root element

    HorizontalLayout {
        spacing: Size.sz2;
        alignment: center;
        padding-left: Size.sz2;
        padding-right: Size.sz2;

        if label != "": TextSm {
            horizontal-alignment: center;
            vertical-alignment: center;
            text: root.label;
            color: label-color;
            horizontal-stretch: 0;
        }
    }

    touchArea := TouchArea {
        clicked => {
            if (enabled) {
                clicked(id);
            }
        }
    }

    states [
        disabled when (!root.enabled != invert-enabled-colors): {
            root.background: bg-color.mix(white, 0.5);
        }
        pressed when touchArea.pressed: {
            root.background: bg-color.mix(black, 0.8);
        }
    ]
}
