// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import {Palette, Size} from "@ui/theme.slint";

export component Icon {
    // Override inherited properties
    width: size;
    height: size;

    // Public properties
    in property <image> source;
    in property <length> size: Size.sz6;
    in property <brush> color: Palette.transparent;

    Image {
        source: source;
        colorize: color;
        width: size;
        height: size;
    }

    @children
}
