[servers."os/update"]
SubscribeUpdateProgress = { id = 0, type = "archiveEvent" }
StartUpdate = { id = 1, type = "move" }
ContinueUpdate = { id = 2, type = "move" }
FirmwareVersion = { id = 4, type = "archive" }
ApplyDownloadedUpdate = { id = 5, type = "move" }
GetUpdateApplied = { id = 6, type = "blockingScalar" }
ClearUpdateApplied = { id = 7, type = "scalar" }
GetUpdateStatus = { id = 8, type = "archive" }
