// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { BasePage } from "@ui/widgets.slint";
import { TR2, TrId } from "../../../../../gen/tr.slint";

import { SettingsNavHeader } from "../../../../../widgets/nav-header.slint";
import { Navigate } from "../../../../../gen/navigate.slint";
import { BackupGlobal } from "../../../../../globals/backup-global.slint";

export component SaveToCardPage inherits BasePage { }
