[servers."os/crypto"]
AesSetup = { id = 1, type = "lendMut", cfg = "keyos" }
AesExecute = { id = 2, type = "lendMut", cfg = "keyos" }
DiskEncryptUnsafe = { id = 3, type = "archive", cfg = "keyos" }
AesClear = { id = 4, type = "scalar", cfg = "keyos" }
# id 5 is unused
Hmac = { id = 6, type = "archive" }
ShamirSplit = { id = 7, type = "archive" }
ShamirRecover = { id = 8, type = "archive" }
ShaInit = { id = 9, type = "archive" }
ShaUpdate = { id = 10, type = "lendMut" }
ShaFinalize = { id = 11, type = "archive" }
ShaAbort = { id = 12, type = "scalar" }
