// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Callbacks as CB } from "../../callbacks.slint";
import { SeedView, SeedViewType } from "../../types.slint";
import { Palette, Size, Importance, CallbackResult, ResultLevel,
         CardColor } from "@ui/theme.slint";
import { CardPill, IconButton, LineCard, Arc, TextLg, TextSm,
         AppHeader, BasePage, PageBody, ContentSection,
         Movable, Link, ResultModal, Dropdown, DropdownOverlay,
         TitledInput, ButtonSection, Button, ConfirmationModal,
         CardColorPicker, CircleIcon } from "@ui/widgets.slint";
import { DetailsProps } from "./props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { EditPageVersion } from "@ui/pages.slint";
import { TR2, TrId } from "../../gen/tr.slint";

export component DetailsPage inherits BasePage {
    in property <DetailsProps> props;

    property <string> new-label: props.seed.label;
    property <int> new-color: props.seed.color;
    property <string> new-account: props.seed.password.account;
    property <string> new-password: props.seed.password.password;
    property <bool> is-delete-modal-open: false;
    property <bool> is-display-modal-open: false;
    property <bool> has-changes: new-label != props.seed.label || (props.seed.seed-type == SeedViewType.password && (new-account != props.seed.password.account || new-password != props.seed.password.password)) || new-color != props.seed.color;
    property <bool> has-error: label-error || (props.seed.seed-type == SeedViewType.password && password-error);
    property <bool> label-error: false;
    property <bool> password-error: false;
    property <CallbackResult> result: {
        success: true,
    };

    VerticalLayout {
        AppHeader {
            title: props.version == EditPageVersion.edit ? TR2.lookup(TrId.ItemDetailsTitle) : TR2.lookup(TrId.ArchivedItemTitle);

            IconButton {
                icon: "chevron-left";
                size: Size.sz8;
                importance: Importance.normal;
                clicked => {
                    Navigate.backward();
                }
            }
        }

        PageBody {
            p-x: Size.sz4;
            p-y: Size.sz4;

            ContentSection {
                HorizontalLayout {
                    spacing: Size.sz4;

                    TitledInput {
                        title: TR2.lookup(TrId.CreateItemItemLabel);
                        placeholder: TR2.lookup(TrId.CreateItemItemLabelFillerText);
                        text: props.seed.label;
                        enabled: props.version != EditPageVersion.archive;

                        caps-mode: sentences;

                        edited(text) => {
                            new-label = text;
                            self.message = CB.validate-edit-label(props.seed.index, text);
                            self.has-notice = self.message != "";
                            label-error = self.has-notice;
                        }
                    }

                    VerticalLayout {
                        spacing: Size.sz2;

                        TextSm {
                            text: TR2.lookup(TrId.ItemDetailsIcon);
                            color: Palette.content-tertiary;
                            horizontal-alignment: TextHorizontalAlignment.center;
                        }

                        CircleIcon {
                            icon: CB.get-icon(props.seed.seed-type);
                            line-color: CardColor.light-copper;
                            shadow: false;
                        }
                    }
                }

                // TODO: make this a widget
                if CB.is-indexed-seed(props.seed.seed-type): VerticalLayout {
                    padding-left: Size.sz4;
                    spacing: Size.sz2;

                    HorizontalLayout {
                        alignment: start;
                        TextSm {
                            text: TR2.lookup(TrId.ItemDetailsInformation);
                            color: Palette.content-tertiary;
                        }
                    }

                    HorizontalLayout {
                        alignment: start;
                        spacing: Size.sz2;

                        TextSm {
                            text: TR2.lookup(TrId.CreateItemType);
                            color: Palette.content-primary;
                            width: 57px;
                        }

                        TextSm {
                            text: CB.get-seed-name(props.seed.seed-type);
                            color: Palette.content-primary;
                        }
                    }

                    HorizontalLayout {
                        alignment: start;
                        spacing: Size.sz2;

                        TextSm {
                            text: TR2.lookup(TrId.CreateItemIndex);
                            color: Palette.content-primary;
                            width: 57px;
                        }

                        TextSm {
                            text: props.seed.indexed-seed.index;
                            color: Palette.content-primary;
                        }
                    }
                }

                if props.seed.seed-type == SeedViewType.password: TitledInput {
                    title: TR2.lookup(TrId.CreateItemAccount);
                    placeholder: TR2.lookup(TrId.CreateItemAccountFillerText);
                    text: props.seed.password.account;
                    caps-mode: sentences;
                    enabled: props.version != EditPageVersion.archive;

                    edited(text) => {
                        new-account = text;
                    }
                }

                if props.seed.seed-type == SeedViewType.password: TitledInput {
                    title: TR2.lookup(TrId.CreateItemPassword);
                    placeholder: TR2.lookup(TrId.CreateItemPasswordFillerText);
                    text: props.seed.password.password;
                    has-notice: self.text == "";
                    show-password: false;
                    enabled: props.version != EditPageVersion.archive;
                    input-type: InputType.password;

                    edited(text) => {
                        new-password = text;
                        self.has-notice = text == "";
                        // TODO: potentially add warning copy
                        // if (self.has-notice) {
                        //     self.message = "Passwords must not be empty";
                        // } else {
                        //     self.message = "";
                        // }
                        password-error = self.has-notice;
                    }
                }

                if props.version != EditPageVersion.archive: CardColorPicker {
                    selected-index: props.seed.color;
                    title: TR2.lookup(TrId.ItemDetailsColor);
                    changed(index) => {
                        new-color = index;
                    }
                }
            }

            ButtonSection {
                if CB.is-indexed-seed(props.seed.seed-type): Button {
                    icon: "scan-qr";
                    label: props.seed.seed-type == SeedViewType.nostr-key ? TR2.lookup(TrId.ItemDetailsNostrKeyViewKey) : TR2.lookup(TrId.ItemDetailsSeedViewSeed);
                    importance: props.version == EditPageVersion.edit ? Importance.primary : Importance.secondary;

                    clicked => {
                        is-display-modal-open = true;
                    }
                }

                if props.version == EditPageVersion.edit && has-changes: Button {
                    icon: "";
                    label: TR2.lookup(TrId.CommonButtonSave);
                    enabled: !has-error;
                    importance: Importance.primary;

                    clicked => {
                        result = CB.is-indexed-seed(props.seed.seed-type) ? CB.edit-indexed(props.seed.index, new-label, new-color) : CB.edit-password(props.seed.index, new-label, new-account, new-password, new-color);
                        if (result.success) {
                            Navigate.backward();
                        }
                    }
                }

                if props.version == EditPageVersion.edit && !has-changes: Button {
                    icon: "archive";
                    label: TR2.lookup(TrId.ItemDetailsArchive);
                    enabled: !has-changes;
                    importance: Importance.secondary;

                    clicked => {
                        CB.set-archived(props.seed.index, true);
                        Navigate.backward();
                    }
                }

                if props.seed.seed-type == SeedViewType.password && props.version == EditPageVersion.archive: Button {
                    icon: "";
                    label: TR2.lookup(TrId.CommonButtonDelete);
                    importance: Importance.negative;

                    clicked => {
                        is-delete-modal-open = true;
                    }
                }

                if props.version == EditPageVersion.archive: Button {
                    icon: "export";
                    label: props.seed.seed-type == SeedViewType.password ? TR2.lookup(TrId.ArchivedItemPasswordRestorePassword) : (props.seed.seed-type == SeedViewType.nostr-key ? TR2.lookup(TrId.ArchivedItemNostrKeyRestoreKey) : TR2.lookup(TrId.ArchivedItemSeedRestoreSeed));
                    importance: Importance.primary;

                    clicked => {
                        CB.set-archived(props.seed.index, false);
                        Navigate.backward();
                    }
                }
            }
        }
    }

    if is-delete-modal-open: ConfirmationModal {
        icon: "alert";
        icon-color: Palette.content-notice;
        title: TR2.lookup(TrId.PasswordDeleteModalHeader);
        text: TR2.format(TrId.PasswordDeleteModalContent1, [
            props.seed.label,
        ]);
        extra-warning: TR2.lookup(TrId.SeedDeleteModalContent2);
        extra-warning-color: Palette.content-notice;
        confirm-button-label: TR2.lookup(TrId.CommonButtonConfirm);
        cancel-button-label: TR2.lookup(TrId.CommonButtonCancel);

        cancel-clicked => {
            is-delete-modal-open = false;
        }

        confirm-clicked => {
            is-delete-modal-open = false;
            CB.delete(props.seed.index);
            Navigate.backward();
        }
    }

    if is-display-modal-open: ConfirmationModal {
        icon: "alert";
        icon-color: Palette.content-notice;
        title: TR2.lookup(TrId.ArchivedItemSeedModalRevealHeader);
        text: props.seed.seed-type == SeedViewType.nostr-key ? TR2.lookup(TrId.ArchivedItemNostrKeyModalRevealContent1) : TR2.lookup(TrId.ArchivedItemSeedModalRevealContent1);
        extra-warning: props.seed.seed-type == SeedViewType.nostr-key ? TR2.lookup(TrId.ArchivedItemNostrKeyModalRevealContent2) : TR2.lookup(TrId.ArchivedItemSeedModalRevealContent2);
        confirm-button-label: TR2.lookup(TrId.CommonButtonConfirm);
        cancel-button-label: TR2.lookup(TrId.CommonButtonCancel);

        cancel-clicked => {
            is-display-modal-open = false;
        }

        confirm-clicked => {
            Navigate.view({ seed: props.seed, version: props.version }, { });
        }
    }

    // This shouldn't happen due to disabling the save button,
    // but it's useful to catch and report unexpected errors
    if !result.success: ResultModal {
        result: result;
        confirm-button-label: TR2.lookup(TrId.CommonButtonConfirm);

        confirm-clicked => {
            result.success = true;
        }
    }
}
