// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Callbacks as CB } from "../../../callbacks.slint";
import { BasePage, AppHeader, IconButton, SeedWords, ButtonSection, Button, QrPages } from "@ui/widgets.slint";
import { Importance, Size } from "@ui/theme.slint";
import { SeedView, SeedViewType } from "../../../types.slint";
import { DetailsProps } from "../props.slint";
import { ViewProps } from "./props.slint";
import { Navigate } from "../../../gen/navigate.slint";
import { TR2, TrId } from "../../../gen/tr.slint";

export component ViewPage inherits BasePage {
    in property <DetailsProps> details-props;
    in property <ViewProps> props;

    property <SeedView> seed: details-props.seed;
    property <bool> qr-view: false;

    pure function get-view-title(seed-type: SeedViewType) -> string {
        if (seed-type == SeedViewType.bitcoin-12 || seed-type == SeedViewType.bitcoin-24) {
            return TR2.lookup(TrId.ViewSeedWordsTitle);
        } else if (seed-type == SeedViewType.nostr-key) {
            return TR2.lookup(TrId.ViewNostrKeyTitle);
        }
        return TR2.lookup(TrId.ViewSeedWordsTitle);
        ;
    }

    VerticalLayout {
        AppHeader {
            title: get-view-title(seed.seed-type);
            side-padding: Size.sz8;

            IconButton {
                icon: "chevron-left";
                size: Size.sz8;
                importance: Importance.normal;
                clicked => {
                    Navigate.backward();
                }
            }

            if seed.seed-type != SeedViewType.nostr-key: IconButton {
                icon: qr-view ? "list" : "scan-qr";
                size: Size.sz8;
                importance: Importance.normal;
                clicked => {
                    qr-view = !qr-view;
                }
            }
        }

        VerticalLayout {
            padding-top: (seed.seed-type == SeedViewType.nostr-key || qr-view) ? Size.sz2 : Size.sz10;
            padding-bottom: Size.sz4;

            if (seed.seed-type != SeedViewType.nostr-key && !qr-view): SeedWords {
                words: CB.get-words(seed.index);
            }

            if (seed.seed-type != SeedViewType.nostr-key && qr-view): QrPages {
                model: [
                    {
                        code: CB.get-standard-seed-qr(seed.index),
                        header: TR2.lookup(TrId.ViewSeedWordsStandardSeedQr),
                    },
                    {
                        code: CB.get-compact-seed-qr(seed.index),
                        header: TR2.lookup(TrId.ViewSeedWordsCompactSeedQr),
                    },
                ];
            }

            if seed.seed-type == SeedViewType.nostr-key: QrPages {
                model: [
                    {
                        code: CB.get-npub-qr(seed.index),
                        header: TR2.lookup(TrId.ArchivedItemNostrKeyPublicKey),
                        footer: CB.get-npub(seed.index),
                        footer-is-address: true,
                    },
                    {
                        code: CB.get-nsec-qr(seed.index),
                        header: TR2.lookup(TrId.ArchivedItemNostrKeyPrivateKey),
                        footer: CB.get-nsec(seed.index),
                        footer-is-address: true,
                    },
                ];
            }

            ButtonSection {
                padding: Size.sz6;
                Button {
                    label: TR2.lookup(TrId.CommonButtonDone);

                    clicked => {
                        Navigate.backward();
                    }
                }
            }
        }
    }
}
