// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

import { TR2, TrId } from "../../../gen/tr.slint";
import { 
    MenuSection,
    MenuSectionLayout,
    MenuActionItem,
    HLine,
    BasePage,
    PageBody
} from "@ui/widgets.slint";

import { Navigate } from "../../../gen/navigate.slint";
import { SettingsNavHeader } from "../../../widgets/nav-header.slint";
import { AdvancedProps } from "props.slint";

export component AdvancedPage inherits BasePage {
    in property <AdvancedProps> props;

    VerticalLayout {
        SettingsNavHeader {
            title: TR2.lookup(TrId.AdvancedMenuHeader);
        }

        PageBody {
            MenuSection {
                title: "";
                MenuSectionLayout {
                    MenuActionItem {
                        first: true;
                        label: TR2.lookup(TrId.AdvancedMenuViewLogs);
                        clicked => {
                            Navigate.view-logs({ });
                        }
                    }

                    HLine { }

                    MenuActionItem {
                        last: true;
                        label: TR2.lookup(TrId.AdvancedMenuEraseDevice);
                        clicked => {
                            Navigate.erase-device({ }, { });
                        }
                    }
                }
            }
        }
    }
}
