// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

export global AboutGlobal {
    in property <string> serial-number: "1234567890";
    in property <string> keyos-version: "1.0.0";
    in property <string> bootloader-version: "1.0.0";
    in property <string> ble-firmware-version: "1.0.0";
    in property <string> ble-bootloader-version: "1.0.0";
    in property <string> master-fingerprint: "";
    in property <string> reversed-fingerprint: "";
}
