// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

export global SettingGlobal {
    callback set-dark-mode(bool);

    in-out property <string> device-name: "Device Name";
    callback set-device-name(string);

    // this is only float, due to the slider being a float
    // we need float type to keep reactivity
    in-out property <float> screen-brightness: 100;
    callback set-screen-brightness(float);

    // Auto Shutdown in seconds.
    // -1 = never
    in-out property <int> auto-lock: 5;
    callback set-auto-lock(int);
    // seconds to human readable string
    pure callback format-auto-lock(int) -> string;

    in-out property <bool> show-security-words: false;
    callback set-show-security-words(bool);

    in property <string> current-keyos-version: "";

    callback factory-reset();
}
