// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { ModalWindow } from "@ui/widgets.slint";
import { Palette, UISize, Utils, Images, CurrentTheme } from "@ui/theme.slint";
import { TR } from "@ui/i18n/i18n.slint";

import { BrowserGlobal, AirlockMode, SortDirection, SortMode } from "./browser/global.slint";
import { FileBrowser } from "./browser/browser.slint";
import { PickerGlobal } from "./picker/global.slint";
import { PickerBody } from "./picker/picker.slint";
import { ModalGlobal } from "./modal/global.slint";

export { Utils, Images, TR, CurrentTheme }
export { BrowserGlobal, PickerGlobal, ModalGlobal }
export { AirlockMode, SortDirection, SortMode }
export * from "gen/exports.slint";

export component AppWindow inherits Window {
    padding: 0;
    width: UISize.screen-width;
    height: PickerGlobal.is-active ? UISize.popup-app-height : UISize.screen-height;
    background: Palette.transparent;

    if PickerGlobal.is-active: ModalWindow {
        PickerBody { }
    }
    if !PickerGlobal.is-active: FileBrowser { }

    forward-focus: focus-scope;
    focus-scope := FocusScope { }
}
