// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette } from "@ui/theme.slint";
import { Size } from "@ui/types.slint";



export component Pagination {
    in property <int> current-page;
    in property <int> total-pages;

    HorizontalLayout {
        spacing: Size.sz2;
        for i in total-pages: Rectangle {
            background: i == current-page ? Palette.content-brand : Palette.content-disabled;
            height: 12px;
            width: 12px;
            border-radius: root.width / 2;
        }
    }
}
