/* automatically generated by rust-bindgen 0.71.1 */

pub const ATCA_CA2_SUPPORT: u32 = 0;
pub const ATCA_CA2_CERT_SUPPORT: u32 = 0;
pub const ATCA_CA_SUPPORT: u32 = 0;
pub const ATCA_TA_SUPPORT: u32 = 0;
pub const ATCA_HOSTLIB_EN: u32 = 0;
pub const ATCA_CHECK_PARAMS_EN: u32 = 1;
pub const ATCACERT_EN: u32 = 1;
pub const ATCA_UNUSED_VAR_CHECK: u32 = 1;
pub const ATCAB_AES_EN: u32 = 1;
pub const ATCAB_AES_GCM_EN: u32 = 1;
pub const ATCAB_CHECKMAC_EN: u32 = 1;
pub const ATCAB_COUNTER_EN: u32 = 1;
pub const ATCAB_DERIVEKEY_EN: u32 = 1;
pub const ATCAB_ECDH_EN: u32 = 1;
pub const ATCAB_ECDH_ENC_EN: u32 = 1;
pub const ATCAB_GENDIG_EN: u32 = 1;
pub const ATCAB_GENKEY_EN: u32 = 1;
pub const ATCAB_GENKEY_MAC_EN: u32 = 1;
pub const ATCAB_HMAC_EN: u32 = 1;
pub const ATCAB_INFO_LATCH_EN: u32 = 1;
pub const ATCAB_KDF_EN: u32 = 1;
pub const ATCAB_LOCK_EN: u32 = 1;
pub const ATCAB_MAC_EN: u32 = 1;
pub const ATCAB_NONCE_EN: u32 = 1;
pub const ATCAB_PRIVWRITE_EN: u32 = 1;
pub const ATCAB_RANDOM_EN: u32 = 1;
pub const ATCAB_READ_EN: u32 = 1;
pub const ATCAB_READ_ENC_EN: u32 = 1;
pub const ATCAB_SECUREBOOT_EN: u32 = 1;
pub const ATCAB_SECUREBOOT_MAC_EN: u32 = 1;
pub const ATCAB_SELFTEST_EN: u32 = 1;
pub const ATCAB_SHA_EN: u32 = 1;
pub const ATCAB_SHA_HMAC_EN: u32 = 1;
pub const ATCAB_SHA_CONTEXT_EN: u32 = 1;
pub const ATCAB_SIGN_EN: u32 = 1;
pub const ATCAB_SIGN_INTERNAL_EN: u32 = 1;
pub const ATCAB_UPDATEEXTRA_EN: u32 = 1;
pub const ATCAB_VERIFY_EN: u32 = 1;
pub const ATCAB_VERIFY_EXTERN_EN: u32 = 1;
pub const ATCAB_VERIFY_MAC_EN: u32 = 1;
pub const ATCAB_VERIFY_STORED_EN: u32 = 1;
pub const ATCAB_VERIFY_VALIDATE_EN: u32 = 1;
pub const ATCAB_WRITE_EN: u32 = 1;
pub const ATCAB_WRITE_ENC_EN: u32 = 1;
pub const ATCAC_SHA1_EN: u32 = 1;
pub const ATCAC_SHA256_EN: u32 = 1;
pub const ATCAC_SHA384_EN: u32 = 0;
pub const ATCAC_SHA512_EN: u32 = 0;
pub const ATCAC_SHA256_HMAC_EN: u32 = 1;
pub const ATCAC_SHA256_HMAC_CTR_EN: u32 = 1;
pub const ATCAC_RANDOM_EN: u32 = 0;
pub const ATCAC_VERIFY_EN: u32 = 0;
pub const ATCAC_SIGN_EN: u32 = 0;
pub const ATCA_LIBRARY_VERSION_DATE: &[u8; 9] = b"20240926\0";
pub const ATCA_LIBRARY_VERSION_MAJOR: u32 = 3;
pub const ATCA_LIBRARY_VERSION_MINOR: u32 = 7;
pub const ATCA_LIBRARY_VERSION_BUILD: u32 = 6;
pub const ATCA_SUCCESS: u32 = 0;
pub const ATCA_CONFIG_ZONE_LOCKED: u32 = 1;
pub const ATCA_DATA_ZONE_LOCKED: u32 = 2;
pub const ATCA_WAKE_FAILED: i32 = -48;
pub const ATCA_CHECKMAC_VERIFY_FAILED: i32 = -47;
pub const ATCA_PARSE_ERROR: i32 = -46;
pub const ATCA_STATUS_CRC: i32 = -44;
pub const ATCA_STATUS_UNKNOWN: i32 = -43;
pub const ATCA_STATUS_ECC: i32 = -42;
pub const ATCA_STATUS_SELFTEST_ERROR: i32 = -41;
pub const ATCA_FUNC_FAIL: i32 = -32;
pub const ATCA_GEN_FAIL: i32 = -31;
pub const ATCA_BAD_PARAM: i32 = -30;
pub const ATCA_INVALID_ID: i32 = -29;
pub const ATCA_INVALID_SIZE: i32 = -28;
pub const ATCA_RX_CRC_ERROR: i32 = -27;
pub const ATCA_RX_FAIL: i32 = -26;
pub const ATCA_RX_NO_RESPONSE: i32 = -25;
pub const ATCA_RESYNC_WITH_WAKEUP: i32 = -24;
pub const ATCA_PARITY_ERROR: i32 = -23;
pub const ATCA_TX_TIMEOUT: i32 = -22;
pub const ATCA_RX_TIMEOUT: i32 = -21;
pub const ATCA_TOO_MANY_COMM_RETRIES: i32 = -20;
pub const ATCA_SMALL_BUFFER: i32 = -19;
pub const ATCA_COMM_FAIL: i32 = -16;
pub const ATCA_TIMEOUT: i32 = -15;
pub const ATCA_BAD_OPCODE: i32 = -14;
pub const ATCA_WAKE_SUCCESS: i32 = -13;
pub const ATCA_EXECUTION_ERROR: i32 = -12;
pub const ATCA_UNIMPLEMENTED: i32 = -11;
pub const ATCA_ASSERT_FAILURE: i32 = -10;
pub const ATCA_TX_FAIL: i32 = -9;
pub const ATCA_NOT_LOCKED: i32 = -8;
pub const ATCA_NO_DEVICES: i32 = -7;
pub const ATCA_HEALTH_TEST_ERROR: i32 = -6;
pub const ATCA_ALLOC_FAILURE: i32 = -5;
pub const ATCA_USE_FLAGS_CONSUMED: i32 = -4;
pub const ATCA_NOT_INITIALIZED: i32 = -3;
pub const ATCA_STATUS_AUTH_BIT: u32 = 64;
pub const ATCA_STATUS_AUTH_BIT_COMPLEMENT: i32 = -65;
pub const ATECC108A: u32 = 1;
pub const ATECC508A: u32 = 2;
pub const ATECC608A: u32 = 3;
pub const ATECC608B: u32 = 3;
pub const ATECC608: u32 = 3;
pub const ATCA_DEV_UNKNOWN: u32 = 126;
pub const ATCA_DEV_INVALID: u32 = 127;
pub const ATCA_POLLING_INIT_TIME_MSEC: u32 = 1;
pub const ATCA_POLLING_FREQUENCY_TIME_MSEC: u32 = 2;
pub const ATCA_POLLING_MAX_TIME_MSEC: u32 = 2500;
pub const ATCA_HAL_CONTROL_WAKE: u32 = 0;
pub const ATCA_HAL_CONTROL_IDLE: u32 = 1;
pub const ATCA_HAL_CONTROL_SLEEP: u32 = 2;
pub const ATCA_HAL_CONTROL_RESET: u32 = 3;
pub const ATCA_HAL_CONTROL_SELECT: u32 = 4;
pub const ATCA_HAL_CONTROL_DESELECT: u32 = 5;
pub const ATCA_HAL_CHANGE_BAUD: u32 = 6;
pub const ATCA_HAL_FLUSH_BUFFER: u32 = 7;
pub const ATCA_HAL_CONTROL_DIRECTION: u32 = 8;
pub const ATCA_SHA256_BLOCK_SIZE: u32 = 64;
pub const ATCA_SHA256_DIGEST_SIZE: u32 = 32;
pub const ATCA_SHA384_BLOCK_SIZE: u32 = 128;
pub const ATCA_SHA384_DIGEST_SIZE: u32 = 48;
pub const ATCA_SHA512_BLOCK_SIZE: u32 = 128;
pub const ATCA_SHA512_DIGEST_SIZE: u32 = 64;
pub const ATCA_AES128_BLOCK_SIZE: u32 = 16;
pub const ATCA_AES128_KEY_SIZE: u32 = 16;
pub const ATCA_AES256_BLOCK_SIZE: u32 = 16;
pub const ATCA_AES256_KEY_SIZE: u32 = 32;
pub const ATCA_ECCP256_MSG_SIZE: u32 = 32;
pub const ATCA_KEY_TYPE_ECCP256: u32 = 0;
pub const ATCA_ECCP256_KEY_SIZE: u32 = 32;
pub const ATCA_ECCP256_PUBKEY_SIZE: u32 = 64;
pub const ATCA_ECCP256_PVTKEY_SIZE: u32 = 32;
pub const ATCA_ECCP256_SIG_SIZE: u32 = 64;
pub const ATCA_ECCP256_OID_SIZE: u32 = 10;
pub const ATCA_ECCP256_ASN1_HDR_SIZE: u32 = 27;
pub const ATCA_MAX_ECC_RSA_PB_KEY_SIZE: u32 = 512;
pub const ATCA_RSA4K_ASN1_HDR_SIZE: u32 = 33;
pub const ATCA_ECC_UNCOMPRESSED_TYPE_OFFSET: u32 = 1;
pub const CALIB_SHA204_EN: u32 = 0;
pub const CALIB_SHA206_EN: u32 = 0;
pub const CALIB_ECC108_EN: u32 = 0;
pub const CALIB_ECC508_EN: u32 = 0;
pub const CALIB_ECC608_EN: u32 = 0;
pub const CALIB_ECC204_EN: u32 = 0;
pub const CALIB_TA010_EN: u32 = 0;
pub const CALIB_SHA104_EN: u32 = 0;
pub const CALIB_SHA105_EN: u32 = 0;
pub const CALIB_DELETE_EN: u32 = 0;
pub const CALIB_INFO_LATCH_EN: u32 = 1;
pub const ATCA_CRYPTO_SHA2_HMAC_CTR_EN: u32 = 1;
pub const ATCAC_PBKDF2_SHA256_EN: u32 = 1;
pub const ATCAC_AES_GCM_EN: u32 = 0;
pub const ATCAC_AES_CMAC_EN: u32 = 0;
pub const ATCA_AES_ENABLE_EN_SHIFT: u32 = 0;
pub const ATCA_AES_ENABLE_EN_MASK: u32 = 1;
pub const ATCA_I2C_ENABLE_EN_SHIFT: u32 = 0;
pub const ATCA_I2C_ENABLE_EN_MASK: u32 = 1;
pub const ATCA_COUNTER_MATCH_EN_SHIFT: u32 = 0;
pub const ATCA_COUNTER_MATCH_EN_MASK: u32 = 1;
pub const ATCA_COUNTER_MATCH_KEY_SHIFT: u32 = 4;
pub const ATCA_COUNTER_MATCH_KEY_MASK: u32 = 240;
pub const ATCA_CHIP_MODE_I2C_EXTRA_SHIFT: u32 = 0;
pub const ATCA_CHIP_MODE_I2C_EXTRA_MASK: u32 = 1;
pub const ATCA_CHIP_MODE_TTL_EN_SHIFT: u32 = 1;
pub const ATCA_CHIP_MODE_TTL_EN_MASK: u32 = 2;
pub const ATCA_CHIP_MODE_WDG_LONG_SHIFT: u32 = 2;
pub const ATCA_CHIP_MODE_WDG_LONG_MASK: u32 = 4;
pub const ATCA_CHIP_MODE_CLK_DIV_SHIFT: u32 = 3;
pub const ATCA_CHIP_MODE_CLK_DIV_MASK: u32 = 248;
pub const ATCA_SLOT_CONFIG_READKEY_SHIFT: u32 = 0;
pub const ATCA_SLOT_CONFIG_READKEY_MASK: u32 = 15;
pub const ATCA_SLOT_CONFIG_NOMAC_SHIFT: u32 = 4;
pub const ATCA_SLOT_CONFIG_NOMAC_MASK: u32 = 16;
pub const ATCA_SLOT_CONFIG_LIMITED_USE_SHIFT: u32 = 5;
pub const ATCA_SLOT_CONFIG_LIMITED_USE_MASK: u32 = 32;
pub const ATCA_SLOT_CONFIG_ENC_READ_SHIFT: u32 = 6;
pub const ATCA_SLOT_CONFIG_ENC_READ_MASK: u32 = 64;
pub const ATCA_SLOT_CONFIG_IS_SECRET_SHIFT: u32 = 7;
pub const ATCA_SLOT_CONFIG_IS_SECRET_MASK: u32 = 128;
pub const ATCA_SLOT_CONFIG_WRITE_KEY_SHIFT: u32 = 8;
pub const ATCA_SLOT_CONFIG_WRITE_CONFIG_SHIFT: u32 = 12;
pub const ATCA_SLOT_CONFIG_EXT_SIG_SHIFT: u32 = 0;
pub const ATCA_SLOT_CONFIG_EXT_SIG_MASK: u32 = 1;
pub const ATCA_SLOT_CONFIG_INT_SIG_SHIFT: u32 = 1;
pub const ATCA_SLOT_CONFIG_INT_SIG_MASK: u32 = 2;
pub const ATCA_SLOT_CONFIG_ECDH_SHIFT: u32 = 2;
pub const ATCA_SLOT_CONFIG_ECDH_MASK: u32 = 4;
pub const ATCA_SLOT_CONFIG_WRITE_ECDH_SHIFT: u32 = 3;
pub const ATCA_SLOT_CONFIG_WRITE_ECDH_MASK: u32 = 8;
pub const ATCA_SLOT_CONFIG_GEN_KEY_SHIFT: u32 = 8;
pub const ATCA_SLOT_CONFIG_GEN_KEY_MASK: u32 = 256;
pub const ATCA_SLOT_CONFIG_PRIV_WRITE_SHIFT: u32 = 9;
pub const ATCA_SLOT_CONFIG_PRIV_WRITE_MASK: u32 = 512;
pub const ATCA_USE_LOCK_ENABLE_SHIFT: u32 = 0;
pub const ATCA_USE_LOCK_ENABLE_MASK: u32 = 15;
pub const ATCA_USE_LOCK_KEY_SHIFT: u32 = 4;
pub const ATCA_USE_LOCK_KEY_MASK: u32 = 240;
pub const ATCA_VOL_KEY_PERM_SLOT_SHIFT: u32 = 0;
pub const ATCA_VOL_KEY_PERM_SLOT_MASK: u32 = 15;
pub const ATCA_VOL_KEY_PERM_EN_SHIFT: u32 = 7;
pub const ATCA_VOL_KEY_PERM_EN_MASK: u32 = 128;
pub const ATCA_SECURE_BOOT_MODE_SHIFT: u32 = 0;
pub const ATCA_SECURE_BOOT_MODE_MASK: u32 = 3;
pub const ATCA_SECURE_BOOT_PERSIST_EN_SHIFT: u32 = 3;
pub const ATCA_SECURE_BOOT_PERSIST_EN_MASK: u32 = 8;
pub const ATCA_SECURE_BOOT_RAND_NONCE_SHIFT: u32 = 4;
pub const ATCA_SECURE_BOOT_RAND_NONCE_MASK: u32 = 16;
pub const ATCA_SECURE_BOOT_DIGEST_SHIFT: u32 = 8;
pub const ATCA_SECURE_BOOT_DIGEST_MASK: u32 = 3840;
pub const ATCA_SECURE_BOOT_PUB_KEY_SHIFT: u32 = 12;
pub const ATCA_SECURE_BOOT_PUB_KEY_MASK: u32 = 61440;
pub const ATCA_CHIP_OPT_POST_EN_SHIFT: u32 = 0;
pub const ATCA_CHIP_OPT_POST_EN_MASK: u32 = 1;
pub const ATCA_CHIP_OPT_IO_PROT_EN_SHIFT: u32 = 1;
pub const ATCA_CHIP_OPT_IO_PROT_EN_MASK: u32 = 2;
pub const ATCA_CHIP_OPT_KDF_AES_EN_SHIFT: u32 = 2;
pub const ATCA_CHIP_OPT_KDF_AES_EN_MASK: u32 = 4;
pub const ATCA_CHIP_OPT_ECDH_PROT_SHIFT: u32 = 8;
pub const ATCA_CHIP_OPT_ECDH_PROT_MASK: u32 = 768;
pub const ATCA_CHIP_OPT_KDF_PROT_SHIFT: u32 = 10;
pub const ATCA_CHIP_OPT_KDF_PROT_MASK: u32 = 3072;
pub const ATCA_CHIP_OPT_IO_PROT_KEY_SHIFT: u32 = 12;
pub const ATCA_KEY_CONFIG_PRIVATE_SHIFT: u32 = 0;
pub const ATCA_KEY_CONFIG_PRIVATE_MASK: u32 = 1;
pub const ATCA_KEY_CONFIG_PUB_INFO_SHIFT: u32 = 1;
pub const ATCA_KEY_CONFIG_PUB_INFO_MASK: u32 = 2;
pub const ATCA_KEY_CONFIG_KEY_TYPE_SHIFT: u32 = 2;
pub const ATCA_KEY_CONFIG_KEY_TYPE_MASK: u32 = 28;
pub const ATCA_KEY_CONFIG_LOCKABLE_SHIFT: u32 = 5;
pub const ATCA_KEY_CONFIG_LOCKABLE_MASK: u32 = 32;
pub const ATCA_KEY_CONFIG_REQ_RANDOM_SHIFT: u32 = 6;
pub const ATCA_KEY_CONFIG_REQ_RANDOM_MASK: u32 = 64;
pub const ATCA_KEY_CONFIG_REQ_AUTH_SHIFT: u32 = 7;
pub const ATCA_KEY_CONFIG_REQ_AUTH_MASK: u32 = 128;
pub const ATCA_KEY_CONFIG_AUTH_KEY_SHIFT: u32 = 8;
pub const ATCA_KEY_CONFIG_AUTH_KEY_MASK: u32 = 3840;
pub const ATCA_KEY_CONFIG_PERSIST_DIS_SHIFT: u32 = 12;
pub const ATCA_KEY_CONFIG_PERSIST_DIS_MASK: u32 = 4096;
pub const ATCA_KEY_CONFIG_RFU_SHIFT: u32 = 13;
pub const ATCA_KEY_CONFIG_RFU_MASK: u32 = 8192;
pub const ATCA_KEY_CONFIG_X509_ID_SHIFT: u32 = 14;
pub const ATCA_KEY_CONFIG_X509_ID_MASK: u32 = 49152;
pub const ATCA_CMD_SIZE_MIN: u32 = 7;
pub const ATCA_BLOCK_SIZE: u32 = 32;
pub const ATCA_WORD_SIZE: u32 = 4;
pub const ATCA_PUB_KEY_PAD: u32 = 4;
pub const ATCA_SERIAL_NUM_SIZE: u32 = 9;
pub const ATCA_KEY_COUNT: u32 = 16;
pub const ATCA_ECC_CONFIG_SIZE: u32 = 128;
pub const ATCA_SHA_CONFIG_SIZE: u32 = 88;
pub const ATCA_CA2_CONFIG_SIZE: u32 = 64;
pub const ATCA_CA2_CONFIG_SLOT_SIZE: u32 = 16;
pub const ATCA_OTP_SIZE: u32 = 64;
pub const ATCA_AES_GFM_SIZE: u32 = 32;
pub const ATCA_CHIPMODE_OFFSET: u32 = 19;
pub const ATCA_COUNT_SIZE: u32 = 1;
pub const ATCA_CRC_SIZE: u32 = 2;
pub const ATCA_PACKET_OVERHEAD: u32 = 3;
pub const ATCA_PUB_KEY_SIZE: u32 = 64;
pub const ATCA_PRIV_KEY_SIZE: u32 = 32;
pub const ATCA_SIG_SIZE: u32 = 64;
pub const ATCA_KEY_SIZE: u32 = 32;
pub const ATCA_RSP_SIZE_32: u32 = 35;
pub const ATCA_COUNT_IDX: u32 = 0;
pub const ATCA_OPCODE_IDX: u32 = 1;
pub const ATCA_PARAM1_IDX: u32 = 2;
pub const ATCA_PARAM2_IDX: u32 = 3;
pub const ATCA_DATA_IDX: u32 = 5;
pub const ATCA_RSP_DATA_IDX: u32 = 1;
pub const ATCA_B283_KEY_TYPE: u32 = 0;
pub const ATCA_K283_KEY_TYPE: u32 = 1;
pub const ATCA_P256_KEY_TYPE: u32 = 4;
pub const ATCA_AES_KEY_TYPE: u32 = 6;
pub const ATCA_SHA_KEY_TYPE: u32 = 7;
pub const ATCA_SHA_DIGEST_SIZE: u32 = 32;
pub const CALIB_SWI_FLAG_WAKE: u32 = 0;
pub const CALIB_SWI_FLAG_CMD: u32 = 119;
pub const CALIB_SWI_FLAG_TX: u32 = 136;
pub const CALIB_SWI_FLAG_IDLE: u32 = 187;
pub const CALIB_SWI_FLAG_SLEEP: u32 = 204;
pub const ATCA_SHA1_DIGEST_SIZE: u32 = 20;
pub const ATCA_SHA2_256_DIGEST_SIZE: u32 = 32;
pub const ATCA_SHA2_256_BLOCK_SIZE: u32 = 64;
pub const ATCA_SHA2_384_DIGEST_SIZE: u32 = 48;
pub const ATCA_SHA2_384_BLOCK_SIZE: u32 = 128;
pub const ATCA_SHA2_512_DIGEST_SIZE: u32 = 64;
pub const ATCA_SHA2_512_BLOCK_SIZE: u32 = 128;
unsafe extern "C" {
    pub fn hal_malloc(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn hal_free(ptr: *mut ::std::os::raw::c_void);
}
pub type ATCA_STATUS = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn atca_trace(status: ATCA_STATUS) -> ATCA_STATUS;
}
pub type ATCADeviceType = u8;
///< Native I2C Driver
pub const ATCAIfaceType_ATCA_I2C_IFACE: ATCAIfaceType = 0;
///< SWI or 1-Wire over UART/USART
pub const ATCAIfaceType_ATCA_SWI_IFACE: ATCAIfaceType = 1;
///< Kit v1 over UART/USART
pub const ATCAIfaceType_ATCA_UART_IFACE: ATCAIfaceType = 2;
///< Native SPI Driver
pub const ATCAIfaceType_ATCA_SPI_IFACE: ATCAIfaceType = 3;
///< Kit v1 over HID
pub const ATCAIfaceType_ATCA_HID_IFACE: ATCAIfaceType = 4;
///< Kit v2 (Binary/Bridging)
pub const ATCAIfaceType_ATCA_KIT_IFACE: ATCAIfaceType = 5;
///< Custom HAL functions provided during interface init
pub const ATCAIfaceType_ATCA_CUSTOM_IFACE: ATCAIfaceType = 6;
///< I2C "Bitbang" Driver
pub const ATCAIfaceType_ATCA_I2C_GPIO_IFACE: ATCAIfaceType = 7;
///< SWI or 1-Wire using a GPIO
pub const ATCAIfaceType_ATCA_SWI_GPIO_IFACE: ATCAIfaceType = 8;
///< SWI or 1-Wire using a GPIO
pub const ATCAIfaceType_ATCA_SPI_GPIO_IFACE: ATCAIfaceType = 9;
pub const ATCAIfaceType_ATCA_UNKNOWN_IFACE: ATCAIfaceType = 254;
pub type ATCAIfaceType = ::std::os::raw::c_uchar;
pub const ATCAKitType_ATCA_KIT_AUTO_IFACE: ATCAKitType = 0;
pub const ATCAKitType_ATCA_KIT_I2C_IFACE: ATCAKitType = 1;
pub const ATCAKitType_ATCA_KIT_SWI_IFACE: ATCAKitType = 2;
pub const ATCAKitType_ATCA_KIT_SPI_IFACE: ATCAKitType = 3;
pub const ATCAKitType_ATCA_KIT_UNKNOWN_IFACE: ATCAKitType = 4;
pub type ATCAKitType = ::std::os::raw::c_uchar;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ATCAIfaceCfg {
    pub iface_type: ATCAIfaceType,
    pub devtype: ATCADeviceType,
    pub __bindgen_anon_1: ATCAIfaceCfg__bindgen_ty_1,
    pub wake_delay: u16,
    pub rx_retries: ::std::os::raw::c_int,
    pub cfg_data: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ATCAIfaceCfg__bindgen_ty_1 {
    pub atcai2c: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1,
    pub atcaswi: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2,
    pub atcaspi: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3,
    pub atcauart: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4,
    pub atcahid: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5,
    pub atcakit: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6,
    pub atcacustom: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1 {
    ///< Device address - the upper 7 bits are the I2c address bits
    pub address: u8,
    pub bus: u8,
    pub baud: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Alignment of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1::address"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1, address) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1::bus"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1, bus) - 1usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1::baud"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_1, baud) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2 {
    pub address: u8,
    pub bus: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2>() - 2usize];
    ["Alignment of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2>() - 1usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2::address"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2, address) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2::bus"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_2, bus) - 1usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3 {
    pub bus: u8,
    pub select_pin: u8,
    pub baud: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3>() - 8usize];
    ["Alignment of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3>() - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3::bus"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3, bus) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3::select_pin"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3, select_pin) - 1usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3::baud"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_3, baud) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4 {
    pub dev_interface: ATCAKitType,
    pub dev_identity: u8,
    pub port: u8,
    pub baud: u32,
    pub wordsize: u8,
    pub parity: u8,
    pub stopbits: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::size_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4>() - 12usize];
    ["Alignment of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::align_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4>() - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4::dev_interface"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4, dev_interface) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4::dev_identity"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4, dev_identity) - 1usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4::port"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4, port) - 2usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4::baud"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4, baud) - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4::wordsize"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4, wordsize) - 8usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4::parity"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4, parity) - 9usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4::stopbits"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_4, stopbits) - 10usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5 {
    pub idx: ::std::os::raw::c_int,
    pub dev_interface: ATCAKitType,
    pub dev_identity: u8,
    pub vid: u32,
    pub pid: u32,
    pub packetsize: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::size_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5>() - 20usize];
    ["Alignment of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::align_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5>() - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5::idx"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5, idx) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5::dev_interface"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5, dev_interface) - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5::dev_identity"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5, dev_identity) - 5usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5::vid"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5, vid) - 8usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5::pid"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5, pid) - 12usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5::packetsize"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_5, packetsize) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6 {
    pub dev_interface: ATCAKitType,
    pub dev_identity: u8,
    pub flags: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6"]
        [::std::mem::size_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6>() - 8usize];
    ["Alignment of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6"]
        [::std::mem::align_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6>() - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6::dev_interface"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6, dev_interface) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6::dev_identity"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6, dev_identity) - 1usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6::flags"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_6, flags) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7 {
    pub halinit: ::std::option::Option<
        unsafe extern "C" fn(
            hal: *mut ::std::os::raw::c_void,
            cfg: *mut ::std::os::raw::c_void,
        ) -> ATCA_STATUS,
    >,
    pub halpostinit:
        ::std::option::Option<unsafe extern "C" fn(iface: *mut ::std::os::raw::c_void) -> ATCA_STATUS>,
    pub halsend: ::std::option::Option<
        unsafe extern "C" fn(
            iface: *mut ::std::os::raw::c_void,
            word_address: u8,
            txdata: *mut u8,
            txlength: ::std::os::raw::c_int,
        ) -> ATCA_STATUS,
    >,
    pub halreceive: ::std::option::Option<
        unsafe extern "C" fn(
            iface: *mut ::std::os::raw::c_void,
            word_address: u8,
            rxdata: *mut u8,
            rxlength: *mut u16,
        ) -> ATCA_STATUS,
    >,
    pub halwake:
        ::std::option::Option<unsafe extern "C" fn(iface: *mut ::std::os::raw::c_void) -> ATCA_STATUS>,
    pub halidle:
        ::std::option::Option<unsafe extern "C" fn(iface: *mut ::std::os::raw::c_void) -> ATCA_STATUS>,
    pub halsleep:
        ::std::option::Option<unsafe extern "C" fn(iface: *mut ::std::os::raw::c_void) -> ATCA_STATUS>,
    pub halrelease:
        ::std::option::Option<unsafe extern "C" fn(hal_data: *mut ::std::os::raw::c_void) -> ATCA_STATUS>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7"]
        [::std::mem::size_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7>() - 32usize];
    ["Alignment of ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7"]
        [::std::mem::align_of::<ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7>() - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7::halinit"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7, halinit) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7::halpostinit"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7, halpostinit) - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7::halsend"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7, halsend) - 8usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7::halreceive"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7, halreceive) - 12usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7::halwake"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7, halwake) - 16usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7::halidle"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7, halidle) - 20usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7::halsleep"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7, halsleep) - 24usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7::halrelease"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1__bindgen_ty_7, halrelease) - 28usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg__bindgen_ty_1"][::std::mem::size_of::<ATCAIfaceCfg__bindgen_ty_1>() - 32usize];
    ["Alignment of ATCAIfaceCfg__bindgen_ty_1"]
        [::std::mem::align_of::<ATCAIfaceCfg__bindgen_ty_1>() - 4usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1::atcai2c"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1, atcai2c) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1::atcaswi"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1, atcaswi) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1::atcaspi"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1, atcaspi) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1::atcauart"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1, atcauart) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1::atcahid"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1, atcahid) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1::atcakit"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1, atcakit) - 0usize];
    ["Offset of field: ATCAIfaceCfg__bindgen_ty_1::atcacustom"]
        [::std::mem::offset_of!(ATCAIfaceCfg__bindgen_ty_1, atcacustom) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAIfaceCfg"][::std::mem::size_of::<ATCAIfaceCfg>() - 48usize];
    ["Alignment of ATCAIfaceCfg"][::std::mem::align_of::<ATCAIfaceCfg>() - 4usize];
    ["Offset of field: ATCAIfaceCfg::iface_type"][::std::mem::offset_of!(ATCAIfaceCfg, iface_type) - 0usize];
    ["Offset of field: ATCAIfaceCfg::devtype"][::std::mem::offset_of!(ATCAIfaceCfg, devtype) - 1usize];
    ["Offset of field: ATCAIfaceCfg::wake_delay"][::std::mem::offset_of!(ATCAIfaceCfg, wake_delay) - 36usize];
    ["Offset of field: ATCAIfaceCfg::rx_retries"][::std::mem::offset_of!(ATCAIfaceCfg, rx_retries) - 40usize];
    ["Offset of field: ATCAIfaceCfg::cfg_data"][::std::mem::offset_of!(ATCAIfaceCfg, cfg_data) - 44usize];
};
pub type ATCAIface = *mut atca_iface;
/// \brief HAL Driver Structure
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAHAL_t {
    pub halinit:
        ::std::option::Option<unsafe extern "C" fn(iface: ATCAIface, cfg: *mut ATCAIfaceCfg) -> ATCA_STATUS>,
    pub halpostinit: ::std::option::Option<unsafe extern "C" fn(iface: ATCAIface) -> ATCA_STATUS>,
    pub halsend: ::std::option::Option<
        unsafe extern "C" fn(
            iface: ATCAIface,
            word_address: u8,
            txdata: *mut u8,
            txlength: ::std::os::raw::c_int,
        ) -> ATCA_STATUS,
    >,
    pub halreceive: ::std::option::Option<
        unsafe extern "C" fn(
            iface: ATCAIface,
            word_address: u8,
            rxdata: *mut u8,
            rxlength: *mut u16,
        ) -> ATCA_STATUS,
    >,
    pub halcontrol: ::std::option::Option<
        unsafe extern "C" fn(
            iface: ATCAIface,
            option: u8,
            param: *mut ::std::os::raw::c_void,
            paramlen: usize,
        ) -> ATCA_STATUS,
    >,
    pub halrelease:
        ::std::option::Option<unsafe extern "C" fn(hal_data: *mut ::std::os::raw::c_void) -> ATCA_STATUS>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAHAL_t"][::std::mem::size_of::<ATCAHAL_t>() - 24usize];
    ["Alignment of ATCAHAL_t"][::std::mem::align_of::<ATCAHAL_t>() - 4usize];
    ["Offset of field: ATCAHAL_t::halinit"][::std::mem::offset_of!(ATCAHAL_t, halinit) - 0usize];
    ["Offset of field: ATCAHAL_t::halpostinit"][::std::mem::offset_of!(ATCAHAL_t, halpostinit) - 4usize];
    ["Offset of field: ATCAHAL_t::halsend"][::std::mem::offset_of!(ATCAHAL_t, halsend) - 8usize];
    ["Offset of field: ATCAHAL_t::halreceive"][::std::mem::offset_of!(ATCAHAL_t, halreceive) - 12usize];
    ["Offset of field: ATCAHAL_t::halcontrol"][::std::mem::offset_of!(ATCAHAL_t, halcontrol) - 16usize];
    ["Offset of field: ATCAHAL_t::halrelease"][::std::mem::offset_of!(ATCAHAL_t, halrelease) - 20usize];
};
/// \brief atca_iface is the context structure for a configured interface
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atca_iface {
    ///< Points to previous defined/given Cfg object, the caller manages this
    pub mIfaceCFG: *mut ATCAIfaceCfg,
    ///< The configured HAL for the interface
    pub hal: *mut ATCAHAL_t,
    ///< When a HAL is not a "native" hal it needs a physical layer to be associated with it
    pub phy: *mut ATCAHAL_t,
    ///< Pointer to HAL specific context/data
    pub hal_data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atca_iface"][::std::mem::size_of::<atca_iface>() - 16usize];
    ["Alignment of atca_iface"][::std::mem::align_of::<atca_iface>() - 4usize];
    ["Offset of field: atca_iface::mIfaceCFG"][::std::mem::offset_of!(atca_iface, mIfaceCFG) - 0usize];
    ["Offset of field: atca_iface::hal"][::std::mem::offset_of!(atca_iface, hal) - 4usize];
    ["Offset of field: atca_iface::phy"][::std::mem::offset_of!(atca_iface, phy) - 8usize];
    ["Offset of field: atca_iface::hal_data"][::std::mem::offset_of!(atca_iface, hal_data) - 12usize];
};
/// \brief atca_iface is the context structure for a configured interface
pub type atca_iface_t = atca_iface;
unsafe extern "C" {
    pub fn atca_iface_is_kit(ca_iface: ATCAIface) -> bool;
}
unsafe extern "C" {
    pub fn atca_iface_is_swi(ca_iface: ATCAIface) -> bool;
}
unsafe extern "C" {
    pub fn atca_iface_get_retries(ca_iface: ATCAIface) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn atca_iface_get_wake_delay(ca_iface: ATCAIface) -> u16;
}
pub const ATCADeviceState_ATCA_DEVICE_STATE_UNKNOWN: ATCADeviceState = 0;
pub const ATCADeviceState_ATCA_DEVICE_STATE_SLEEP: ATCADeviceState = 1;
pub const ATCADeviceState_ATCA_DEVICE_STATE_IDLE: ATCADeviceState = 2;
pub const ATCADeviceState_ATCA_DEVICE_STATE_ACTIVE: ATCADeviceState = 3;
/// \brief ATCADeviceState says about device state
pub type ATCADeviceState = ::std::os::raw::c_uchar;
/// \brief Callback function to clean up the session context
pub type ctx_cb = ::std::option::Option<unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void)>;
/// \brief atca_device is the C object backing ATCADevice.  See the atca_device.h file for
/// details on the ATCADevice methods
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atca_device {
    ///< Physical interface
    pub mIface: atca_iface_t,
    ///< Device Power State
    pub device_state: u8,
    pub clock_divider: u8,
    pub execution_time_msec: u16,
    pub session_ctx: *mut ::std::os::raw::c_void,
    pub session_cb: ctx_cb,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atca_device"][::std::mem::size_of::<atca_device>() - 28usize];
    ["Alignment of atca_device"][::std::mem::align_of::<atca_device>() - 4usize];
    ["Offset of field: atca_device::mIface"][::std::mem::offset_of!(atca_device, mIface) - 0usize];
    ["Offset of field: atca_device::device_state"]
        [::std::mem::offset_of!(atca_device, device_state) - 16usize];
    ["Offset of field: atca_device::clock_divider"]
        [::std::mem::offset_of!(atca_device, clock_divider) - 17usize];
    ["Offset of field: atca_device::execution_time_msec"]
        [::std::mem::offset_of!(atca_device, execution_time_msec) - 18usize];
    ["Offset of field: atca_device::session_ctx"][::std::mem::offset_of!(atca_device, session_ctx) - 20usize];
    ["Offset of field: atca_device::session_cb"][::std::mem::offset_of!(atca_device, session_cb) - 24usize];
};
pub type ATCADevice = *mut atca_device;
unsafe extern "C" {
    pub fn atcab_bin2hex(
        bin: *const u8,
        bin_size: usize,
        hex: *mut ::std::os::raw::c_char,
        hex_size: *mut usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_bin2hex_(
        bin: *const u8,
        bin_size: usize,
        hex: *mut ::std::os::raw::c_char,
        hex_size: *mut usize,
        is_pretty: bool,
        is_space: bool,
        is_upper: bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_hex2bin(
        ascii_hex: *const ::std::os::raw::c_char,
        ascii_hex_len: usize,
        binary: *mut u8,
        bin_len: *mut usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_hex2bin_(
        hex: *const ::std::os::raw::c_char,
        hex_size: usize,
        bin: *mut u8,
        bin_size: *mut usize,
        is_space: bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_b64rules_default() -> *const u8;
}
unsafe extern "C" {
    pub fn atcab_b64rules_mime() -> *const u8;
}
unsafe extern "C" {
    pub fn atcab_b64rules_urlsafe() -> *const u8;
}
unsafe extern "C" {
    pub fn atcab_base64decode_(
        encoded: *const ::std::os::raw::c_char,
        encoded_size: usize,
        data: *mut u8,
        data_size: *mut usize,
        rules: *const u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_base64encode(
        byte_array: *const u8,
        array_len: usize,
        encoded: *mut ::std::os::raw::c_char,
        encoded_len: *mut usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_base64encode_(
        data: *const u8,
        data_size: usize,
        encoded: *mut ::std::os::raw::c_char,
        encoded_size: *mut usize,
        rules: *const u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_base64decode(
        encoded: *const ::std::os::raw::c_char,
        encoded_len: usize,
        byte_array: *mut u8,
        array_len: *mut usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_reversal(
        bin: *const u8,
        bin_size: usize,
        dest: *mut u8,
        dest_size: *mut usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_memset_s(
        dest: *mut ::std::os::raw::c_void,
        destsz: usize,
        ch: ::std::os::raw::c_int,
        count: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn atcab_pointer_delta(
        start: *const ::std::os::raw::c_void,
        end: *const ::std::os::raw::c_void,
    ) -> usize;
}
/// \defgroup hal_ Hardware abstraction layer (hal_)
///
/// \brief
/// These methods define the hardware abstraction layer for communicating with a CryptoAuth device
///
///@{
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atca_hal_kit_phy_t {
    ///< Must be a blocking send
    pub send: ::std::option::Option<
        unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void, txdata: *mut u8, txlen: u16) -> ATCA_STATUS,
    >,
    ///< Must be a blocking receive
    pub recv: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            rxdata: *mut u8,
            rxlen: *mut u16,
        ) -> ATCA_STATUS,
    >,
    ///< Allocate a phy packet
    pub packet_alloc:
        ::std::option::Option<unsafe extern "C" fn(bytes: usize) -> *mut ::std::os::raw::c_void>,
    ///< Free a phy packet
    pub packet_free: ::std::option::Option<unsafe extern "C" fn(packet: *mut ::std::os::raw::c_void)>,
    ///< Physical layer context
    pub hal_data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atca_hal_kit_phy_t"][::std::mem::size_of::<atca_hal_kit_phy_t>() - 20usize];
    ["Alignment of atca_hal_kit_phy_t"][::std::mem::align_of::<atca_hal_kit_phy_t>() - 4usize];
    ["Offset of field: atca_hal_kit_phy_t::send"][::std::mem::offset_of!(atca_hal_kit_phy_t, send) - 0usize];
    ["Offset of field: atca_hal_kit_phy_t::recv"][::std::mem::offset_of!(atca_hal_kit_phy_t, recv) - 4usize];
    ["Offset of field: atca_hal_kit_phy_t::packet_alloc"]
        [::std::mem::offset_of!(atca_hal_kit_phy_t, packet_alloc) - 8usize];
    ["Offset of field: atca_hal_kit_phy_t::packet_free"]
        [::std::mem::offset_of!(atca_hal_kit_phy_t, packet_free) - 12usize];
    ["Offset of field: atca_hal_kit_phy_t::hal_data"]
        [::std::mem::offset_of!(atca_hal_kit_phy_t, hal_data) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atca_hal_shm_t {
    pub recordedPID: ::std::os::raw::c_int,
    pub sessionID: u8,
    pub index: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atca_hal_shm_t"][::std::mem::size_of::<atca_hal_shm_t>() - 8usize];
    ["Alignment of atca_hal_shm_t"][::std::mem::align_of::<atca_hal_shm_t>() - 4usize];
    ["Offset of field: atca_hal_shm_t::recordedPID"]
        [::std::mem::offset_of!(atca_hal_shm_t, recordedPID) - 0usize];
    ["Offset of field: atca_hal_shm_t::sessionID"]
        [::std::mem::offset_of!(atca_hal_shm_t, sessionID) - 4usize];
    ["Offset of field: atca_hal_shm_t::index"][::std::mem::offset_of!(atca_hal_shm_t, index) - 5usize];
};
unsafe extern "C" {
    pub fn hal_iface_init(
        cfg: *mut ATCAIfaceCfg,
        hal: *mut *mut ATCAHAL_t,
        phy: *mut *mut ATCAHAL_t,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_iface_release(iface_type: ATCAIfaceType, hal_data: *mut ::std::os::raw::c_void)
        -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_check_wake(response: *const u8, response_size: ::std::os::raw::c_int) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atca_delay_ms(ms: u32);
}
unsafe extern "C" {
    pub fn atca_delay_us(us: u32);
}
unsafe extern "C" {
    /// \brief Timer API implemented at the HAL level
    pub fn hal_delay_ms(delay: u32);
}
unsafe extern "C" {
    pub fn hal_delay_us(delay: u32);
}
/// \brief Generic mutex type definition for most systems
pub type hal_mutex_t = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    /// \brief Optional hal interfaces
    pub fn hal_create_mutex(
        ppMutex: *mut *mut ::std::os::raw::c_void,
        pName: *const ::std::os::raw::c_char,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_init_mutex(pMutex: *mut ::std::os::raw::c_void, shared: bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_destroy_mutex(pMutex: *mut ::std::os::raw::c_void) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_lock_mutex(pMutex: *mut ::std::os::raw::c_void) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_unlock_mutex(pMutex: *mut ::std::os::raw::c_void) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_alloc_shared(
        pShared: *mut *mut ::std::os::raw::c_void,
        size: usize,
        pName: *const ::std::os::raw::c_char,
        initialized: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_free_shared(pShared: *mut ::std::os::raw::c_void, size: usize) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_iface_register_hal(
        iface_type: ATCAIfaceType,
        hal: *mut ATCAHAL_t,
        old_hal: *mut *mut ATCAHAL_t,
        phy: *mut ATCAHAL_t,
        old_phy: *mut *mut ATCAHAL_t,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn hal_is_command_word(word_address: u8) -> u8;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ATCAPacket {
    pub reserved: u8,
    pub txsize: u8,
    pub opcode: u8,
    pub param1: u8,
    pub param2: u16,
    pub data: [u8; 192usize],
    pub execTime: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ATCAPacket"][::std::mem::size_of::<ATCAPacket>() - 200usize];
    ["Alignment of ATCAPacket"][::std::mem::align_of::<ATCAPacket>() - 2usize];
    ["Offset of field: ATCAPacket::reserved"][::std::mem::offset_of!(ATCAPacket, reserved) - 0usize];
    ["Offset of field: ATCAPacket::txsize"][::std::mem::offset_of!(ATCAPacket, txsize) - 1usize];
    ["Offset of field: ATCAPacket::opcode"][::std::mem::offset_of!(ATCAPacket, opcode) - 2usize];
    ["Offset of field: ATCAPacket::param1"][::std::mem::offset_of!(ATCAPacket, param1) - 3usize];
    ["Offset of field: ATCAPacket::param2"][::std::mem::offset_of!(ATCAPacket, param2) - 4usize];
    ["Offset of field: ATCAPacket::data"][::std::mem::offset_of!(ATCAPacket, data) - 6usize];
    ["Offset of field: ATCAPacket::execTime"][::std::mem::offset_of!(ATCAPacket, execTime) - 198usize];
};
unsafe extern "C" {
    pub fn calib_get_execution_time(opcode: u8, device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_execute_send(
        device: ATCADevice,
        word_address: u8,
        txdata: *mut u8,
        txlength: u16,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_execute_receive(
        device: ATCADevice,
        device_address: u8,
        rxdata: *mut u8,
        rxlength: *mut u16,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_execute_command(packet: *mut ATCAPacket, device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_wakeup_i2c(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_wakeup(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_idle(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sleep(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_exit(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_get_addr(zone: u8, slot: u16, block: u8, offset: u8, addr: *mut u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_get_zone_size(device: ATCADevice, zone: u8, slot: u16, size: *mut usize) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_ca2_get_addr(zone: u8, slot: u16, block: u8, offset: u8, addr: *mut u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_is_locked(device: ATCADevice, zone: u8, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_is_slot_locked(device: ATCADevice, slot: u16, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_ca2_is_locked(device: ATCADevice, zone: u8, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_ca2_is_data_locked(device: ATCADevice, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_ca2_is_config_locked(device: ATCADevice, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_get_devicetype(revision: *mut [u8; 4usize]) -> ATCADeviceType;
}
unsafe extern "C" {
    pub fn calib_is_locked_ext(device: ATCADevice, zone: u8, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_is_private(device: ATCADevice, slot: u16, is_private: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_checkmac_base(
        device: ATCADevice,
        mode: u8,
        key_id: u16,
        challenge: *const u8,
        response: *const u8,
        other_data: *const u8,
        resp_mac: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_checkmac(
        device: ATCADevice,
        mode: u8,
        key_id: u16,
        challenge: *const u8,
        response: *const u8,
        other_data: *const u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_checkmac_with_response_mac(
        device: ATCADevice,
        mode: u8,
        challenge: *const u8,
        response: *const u8,
        other_data: *const u8,
        mac: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_counter(
        device: ATCADevice,
        mode: u8,
        counter_id: u16,
        counter_value: *mut u32,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_counter_increment(
        device: ATCADevice,
        counter_id: u16,
        counter_value: *mut u32,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_counter_read(device: ATCADevice, counter_id: u16, counter_value: *mut u32) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_gendig(
        device: ATCADevice,
        zone: u8,
        key_id: u16,
        other_data: *const u8,
        other_data_size: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_genkey_base(
        device: ATCADevice,
        mode: u8,
        key_id: u16,
        other_data: *const u8,
        public_key: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_genkey(device: ATCADevice, key_id: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_get_pubkey(device: ATCADevice, key_id: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_info_base(device: ATCADevice, mode: u8, param2: u16, out_data: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_info(device: ATCADevice, revision: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_info_privkey_valid(device: ATCADevice, key_id: u16, is_valid: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_info_set_latch(device: ATCADevice, state: bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_info_get_latch(device: ATCADevice, state: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_lock(device: ATCADevice, mode: u8, summary_crc: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_lock_config_zone(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_lock_config_zone_crc(device: ATCADevice, summary_crc: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_lock_data_zone(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_lock_data_zone_crc(device: ATCADevice, summary_crc: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_lock_data_slot(device: ATCADevice, slot: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_mac(
        device: ATCADevice,
        mode: u8,
        key_id: u16,
        challenge: *const u8,
        digest: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_nonce_base(
        device: ATCADevice,
        mode: u8,
        param2: u16,
        num_in: *const u8,
        rand_out: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_nonce(device: ATCADevice, num_in: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_nonce_load(
        device: ATCADevice,
        target: u8,
        num_in: *const u8,
        num_in_size: u16,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_nonce_rand(device: ATCADevice, num_in: *const u8, rand_out: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_challenge(device: ATCADevice, num_in: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_challenge_seed_update(
        device: ATCADevice,
        num_in: *const u8,
        rand_out: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_nonce_gen_session_key(
        device: ATCADevice,
        param2: u16,
        num_in: *mut u8,
        rand_out: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_get_numin_size(mode: u8, length: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_priv_write(
        device: ATCADevice,
        key_id: u16,
        priv_key: *const [u8; 36usize],
        write_key_id: u16,
        write_key: *const [u8; 32usize],
        num_in: *const [u8; 20usize],
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_zone(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        block: u8,
        offset: u8,
        data: *mut u8,
        len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_bytes_zone(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        offset: usize,
        data: *mut u8,
        length: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_serial_number(device: ATCADevice, serial_number: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sha_compare_config(expected: *mut u8, other: *mut u8) -> bool;
}
unsafe extern "C" {
    pub fn calib_ecc_compare_config(expected: *mut u8, other: *mut u8) -> bool;
}
unsafe extern "C" {
    pub fn calib_ecc608_compare_config(expected: *mut u8, other: *mut u8) -> bool;
}
unsafe extern "C" {
    pub fn calib_read_sig(device: ATCADevice, slot: u16, sig: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_config_zone(device: ATCADevice, config_data: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_cmp_config_zone(
        device: ATCADevice,
        config_data: *mut u8,
        same_config: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_zone_ext(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        block: u8,
        offset: u8,
        data: *mut u8,
        len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_bytes_zone_ext(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        offset: usize,
        data: *mut u8,
        length: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_pubkey(device: ATCADevice, slot: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_serial_number_ext(device: ATCADevice, serial_number: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_read_enc(
        device: ATCADevice,
        key_id: u16,
        block: u8,
        data: *mut u8,
        enc_key: *const u8,
        enc_key_id: u16,
        num_in: *const [u8; 20usize],
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_selftest(device: ATCADevice, mode: u8, param2: u16, result: *mut u8) -> ATCA_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atca_sha256_ctx {
    ///!< Total number of message bytes processed
    pub total_msg_size: u32,
    ///!< Number of bytes in current block
    pub block_size: u32,
    ///!< Unprocessed message storage
    pub block: [u8; 128usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atca_sha256_ctx"][::std::mem::size_of::<atca_sha256_ctx>() - 136usize];
    ["Alignment of atca_sha256_ctx"][::std::mem::align_of::<atca_sha256_ctx>() - 4usize];
    ["Offset of field: atca_sha256_ctx::total_msg_size"]
        [::std::mem::offset_of!(atca_sha256_ctx, total_msg_size) - 0usize];
    ["Offset of field: atca_sha256_ctx::block_size"]
        [::std::mem::offset_of!(atca_sha256_ctx, block_size) - 4usize];
    ["Offset of field: atca_sha256_ctx::block"][::std::mem::offset_of!(atca_sha256_ctx, block) - 8usize];
};
pub type atca_sha256_ctx_t = atca_sha256_ctx;
pub type atca_hmac_sha256_ctx_t = atca_sha256_ctx_t;
unsafe extern "C" {
    pub fn calib_sha_base(
        device: ATCADevice,
        mode: u8,
        length: u16,
        message: *const u8,
        data_out: *mut u8,
        data_out_size: *mut u16,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sha_start(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sha_update(device: ATCADevice, message: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sha_end(device: ATCADevice, digest: *mut u8, length: u16, message: *const u8)
        -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sha_read_context(
        device: ATCADevice,
        context: *mut u8,
        context_size: *mut u16,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sha_write_context(device: ATCADevice, context: *const u8, context_size: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sha(device: ATCADevice, length: u16, message: *const u8, digest: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_hw_sha2_256(
        device: ATCADevice,
        data: *const u8,
        data_size: usize,
        digest: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_hw_sha2_256_init(device: ATCADevice, ctx: *mut atca_sha256_ctx_t) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_hw_sha2_256_update(
        device: ATCADevice,
        ctx: *mut atca_sha256_ctx_t,
        data: *const u8,
        data_size: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_hw_sha2_256_finish(
        device: ATCADevice,
        ctx: *mut atca_sha256_ctx_t,
        digest: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sign_base(device: ATCADevice, mode: u8, key_id: u16, signature: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sign(device: ATCADevice, key_id: u16, msg: *const u8, signature: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sign_ext(device: ATCADevice, key_id: u16, msg: *const u8, signature: *mut u8)
        -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_sign_internal(
        device: ATCADevice,
        key_id: u16,
        is_invalidate: bool,
        is_full_sn: bool,
        signature: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_verify(
        device: ATCADevice,
        mode: u8,
        key_id: u16,
        signature: *const u8,
        public_key: *const u8,
        other_data: *const u8,
        mac: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_verify_stored(
        device: ATCADevice,
        message: *const u8,
        signature: *const u8,
        key_id: u16,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_verify_stored_with_tempkey(
        device: ATCADevice,
        signature: *const u8,
        key_id: u16,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write(
        device: ATCADevice,
        zone: u8,
        address: u16,
        value: *const u8,
        mac: *const u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_zone(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        block: u8,
        offset: u8,
        data: *const u8,
        len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_bytes_zone(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        offset_bytes: usize,
        data: *const u8,
        length: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_config_zone(device: ATCADevice, config_data: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_config_counter(device: ATCADevice, counter_id: u16, counter_value: u32)
        -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_ext(
        device: ATCADevice,
        zone: u8,
        address: u16,
        value: *const u8,
        mac: *const u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_zone_ext(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        block: u8,
        offset: u8,
        data: *const u8,
        len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_bytes_zone_ext(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        offset_bytes: usize,
        data: *const u8,
        length: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_config_zone_ext(device: ATCADevice, config_data: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_config_counter_ext(
        device: ATCADevice,
        counter_id: u16,
        counter_value: u32,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_write_pubkey(device: ATCADevice, slot: u16, public_key: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn calib_packet_alloc() -> *mut ATCAPacket;
}
unsafe extern "C" {
    pub fn calib_packet_free(packet: *mut ATCAPacket);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atcac_sha1_ctx {
    pub pad: [u32; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atcac_sha1_ctx"][::std::mem::size_of::<atcac_sha1_ctx>() - 128usize];
    ["Alignment of atcac_sha1_ctx"][::std::mem::align_of::<atcac_sha1_ctx>() - 4usize];
    ["Offset of field: atcac_sha1_ctx::pad"][::std::mem::offset_of!(atcac_sha1_ctx, pad) - 0usize];
};
pub type atcac_sha1_ctx_t = atcac_sha1_ctx;
unsafe extern "C" {
    pub fn atcac_sw_sha1_init(ctx: *mut atcac_sha1_ctx) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sw_sha1_update(ctx: *mut atcac_sha1_ctx, data: *const u8, data_size: usize) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sw_sha1_finish(ctx: *mut atcac_sha1_ctx, digest: *mut [u8; 20usize]) -> ATCA_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atcac_sha2_256_ctx {
    pub pad: [u32; 48usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atcac_sha2_256_ctx"][::std::mem::size_of::<atcac_sha2_256_ctx>() - 192usize];
    ["Alignment of atcac_sha2_256_ctx"][::std::mem::align_of::<atcac_sha2_256_ctx>() - 4usize];
    ["Offset of field: atcac_sha2_256_ctx::pad"][::std::mem::offset_of!(atcac_sha2_256_ctx, pad) - 0usize];
};
pub type atcac_sha2_256_ctx_t = atcac_sha2_256_ctx;
unsafe extern "C" {
    pub fn atcac_sw_sha2_256_init(ctx: *mut atcac_sha2_256_ctx) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sw_sha2_256_update(
        ctx: *mut atcac_sha2_256_ctx,
        data: *const u8,
        data_size: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sw_sha2_256_finish(ctx: *mut atcac_sha2_256_ctx, digest: *mut [u8; 32usize]) -> ATCA_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atcac_hmac_ctx {
    pub sha256_ctx: *mut atcac_sha2_256_ctx_t,
    pub ipad: [u8; 64usize],
    pub opad: [u8; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atcac_hmac_ctx"][::std::mem::size_of::<atcac_hmac_ctx>() - 132usize];
    ["Alignment of atcac_hmac_ctx"][::std::mem::align_of::<atcac_hmac_ctx>() - 4usize];
    ["Offset of field: atcac_hmac_ctx::sha256_ctx"]
        [::std::mem::offset_of!(atcac_hmac_ctx, sha256_ctx) - 0usize];
    ["Offset of field: atcac_hmac_ctx::ipad"][::std::mem::offset_of!(atcac_hmac_ctx, ipad) - 4usize];
    ["Offset of field: atcac_hmac_ctx::opad"][::std::mem::offset_of!(atcac_hmac_ctx, opad) - 68usize];
};
pub type atcac_hmac_ctx_t = atcac_hmac_ctx;
unsafe extern "C" {
    pub fn atcac_sha256_hmac_init(
        ctx: *mut atcac_hmac_ctx,
        sha256_ctx: *mut atcac_sha2_256_ctx,
        key: *const u8,
        key_len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sha256_hmac_update(
        ctx: *mut atcac_hmac_ctx,
        data: *const u8,
        data_size: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sha256_hmac_finish(
        ctx: *mut atcac_hmac_ctx,
        digest: *mut u8,
        digest_len: *mut usize,
    ) -> ATCA_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atcac_aes_cmac_ctx {
    pub ctx_ptr: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atcac_aes_cmac_ctx"][::std::mem::size_of::<atcac_aes_cmac_ctx>() - 4usize];
    ["Alignment of atcac_aes_cmac_ctx"][::std::mem::align_of::<atcac_aes_cmac_ctx>() - 4usize];
    ["Offset of field: atcac_aes_cmac_ctx::ctx_ptr"]
        [::std::mem::offset_of!(atcac_aes_cmac_ctx, ctx_ptr) - 0usize];
};
pub type atcac_aes_cmac_ctx_t = atcac_aes_cmac_ctx;
unsafe extern "C" {
    pub fn atcac_aes_cmac_init(ctx: *mut atcac_aes_cmac_ctx, key: *const u8, key_len: u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_cmac_update(
        ctx: *mut atcac_aes_cmac_ctx,
        data: *const u8,
        data_size: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_cmac_finish(
        ctx: *mut atcac_aes_cmac_ctx,
        cmac: *mut u8,
        cmac_size: *mut usize,
    ) -> ATCA_STATUS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atcac_aes_gcm_ctx {
    pub ctx_ptr: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of atcac_aes_gcm_ctx"][::std::mem::size_of::<atcac_aes_gcm_ctx>() - 4usize];
    ["Alignment of atcac_aes_gcm_ctx"][::std::mem::align_of::<atcac_aes_gcm_ctx>() - 4usize];
    ["Offset of field: atcac_aes_gcm_ctx::ctx_ptr"]
        [::std::mem::offset_of!(atcac_aes_gcm_ctx, ctx_ptr) - 0usize];
};
pub type atcac_aes_gcm_ctx_t = atcac_aes_gcm_ctx;
unsafe extern "C" {
    pub fn atcac_aes_gcm_encrypt_start(
        ctx: *mut atcac_aes_gcm_ctx,
        key: *const u8,
        key_len: u8,
        iv: *const u8,
        iv_len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_gcm_decrypt_start(
        ctx: *mut atcac_aes_gcm_ctx,
        key: *const u8,
        key_len: u8,
        iv: *const u8,
        iv_len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_gcm_encrypt(
        ctx: *mut atcac_aes_gcm_ctx,
        plaintext: *const u8,
        pt_len: usize,
        ciphertext: *mut u8,
        tag: *mut u8,
        tag_len: usize,
        aad: *const u8,
        aad_len: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_gcm_decrypt(
        ctx: *mut atcac_aes_gcm_ctx,
        ciphertext: *const u8,
        ct_len: usize,
        plaintext: *mut u8,
        tag: *const u8,
        tag_len: usize,
        aad: *const u8,
        aad_len: usize,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_gcm_aad_update(
        ctx: *mut atcac_aes_gcm_ctx,
        aad: *const u8,
        aad_len: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_gcm_encrypt_update(
        ctx: *mut atcac_aes_gcm_ctx,
        plaintext: *const u8,
        pt_len: usize,
        ciphertext: *mut u8,
        ct_len: *mut usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_gcm_encrypt_finish(
        ctx: *mut atcac_aes_gcm_ctx,
        tag: *mut u8,
        tag_len: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_gcm_decrypt_update(
        ctx: *mut atcac_aes_gcm_ctx,
        ciphertext: *const u8,
        ct_len: usize,
        plaintext: *mut u8,
        pt_len: *mut usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_aes_gcm_decrypt_finish(
        ctx: *mut atcac_aes_gcm_ctx,
        tag: *const u8,
        tag_len: usize,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_pbkdf2_sha256(
        iter: u32,
        password: *const u8,
        password_len: usize,
        salt: *const u8,
        salt_len: usize,
        result: *mut u8,
        result_len: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sw_sha2_256(data: *const u8, data_size: usize, digest: *mut [u8; 32usize]) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sha256_hmac_ctr_iteration(
        ctx: *mut atcac_hmac_ctx,
        iteration: u8,
        length: u16,
        label: *const u8,
        label_len: usize,
        data: *const u8,
        data_len: usize,
        digest: *mut [u8; 32usize],
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcac_sha256_hmac_counter(
        key: *mut u8,
        key_len: usize,
        label: *const u8,
        label_len: usize,
        data: *const u8,
        data_len: usize,
        digest: *mut u8,
        diglen: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_version(ver_str: *mut ::std::os::raw::c_char) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_init_ext(device: *mut ATCADevice, cfg: *mut ATCAIfaceCfg) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_init(cfg: *mut ATCAIfaceCfg) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_init_device(ca_device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_release_ext(device: *mut ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_release() -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_get_device() -> ATCADevice;
}
unsafe extern "C" {
    pub fn atcab_get_device_type_ext(device: ATCADevice) -> ATCADeviceType;
}
unsafe extern "C" {
    pub fn atcab_get_device_type() -> ATCADeviceType;
}
unsafe extern "C" {
    pub fn atcab_get_device_address(device: ATCADevice) -> u8;
}
unsafe extern "C" {
    pub fn atcab_is_ca_device(dev_type: ATCADeviceType) -> bool;
}
unsafe extern "C" {
    pub fn atcab_is_ca2_device(dev_type: ATCADeviceType) -> bool;
}
unsafe extern "C" {
    pub fn atcab_is_ta_device(dev_type: ATCADeviceType) -> bool;
}
unsafe extern "C" {
    pub fn atcab_pbkdf2_sha256_ext(
        device: ATCADevice,
        iter: u32,
        slot: u16,
        salt: *const u8,
        salt_len: usize,
        result: *mut u8,
        result_len: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_pbkdf2_sha256(
        iter: u32,
        slot: u16,
        salt: *const u8,
        salt_len: usize,
        result: *mut u8,
        result_len: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_wakeup() -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_idle() -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sleep() -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_get_zone_size(zone: u8, slot: u16, size: *mut usize) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_get_zone_size_ext(device: ATCADevice, zone: u8, slot: u16, size: *mut usize) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_aes(mode: u8, key_id: u16, aes_in: *const u8, aes_out: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_aes_encrypt(
        key_id: u16,
        key_block: u8,
        plaintext: *const u8,
        ciphertext: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_aes_encrypt_ext(
        device: ATCADevice,
        key_id: u16,
        key_block: u8,
        plaintext: *const u8,
        ciphertext: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_aes_decrypt(
        key_id: u16,
        key_block: u8,
        ciphertext: *const u8,
        plaintext: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_aes_decrypt_ext(
        device: ATCADevice,
        key_id: u16,
        key_block: u8,
        ciphertext: *const u8,
        plaintext: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_aes_gfm(h: *const u8, input: *const u8, output: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_checkmac(
        mode: u8,
        key_id: u16,
        challenge: *const u8,
        response: *const u8,
        other_data: *const u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_checkmac_with_response_mac(
        mode: u8,
        challenge: *const u8,
        response: *const u8,
        other_data: *const u8,
        mac: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_counter(mode: u8, counter_id: u16, counter_value: *mut u32) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_counter_increment(counter_id: u16, counter_value: *mut u32) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_counter_read(counter_id: u16, counter_value: *mut u32) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_derivekey(mode: u8, key_id: u16, mac: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_derivekey_ext(device: ATCADevice, mode: u8, key_id: u16, mac: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_ecdh_base(
        mode: u8,
        key_id: u16,
        public_key: *const u8,
        pms: *mut u8,
        out_nonce: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_ecdh(key_id: u16, public_key: *const u8, pms: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_ecdh_enc(
        key_id: u16,
        public_key: *const u8,
        pms: *mut u8,
        read_key: *const u8,
        read_key_id: u16,
        num_in: *const [u8; 20usize],
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_ecdh_ioenc(
        key_id: u16,
        public_key: *const u8,
        pms: *mut u8,
        io_key: *const u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_ecdh_tempkey(public_key: *const u8, pms: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_ecdh_tempkey_ioenc(public_key: *const u8, pms: *mut u8, io_key: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_gendig(zone: u8, key_id: u16, other_data: *const u8, other_data_size: u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_gendivkey(other_data: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_genkey_base(
        mode: u8,
        key_id: u16,
        other_data: *const u8,
        public_key: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_genkey(key_id: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_genkey_ext(device: ATCADevice, key_id: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_get_pubkey(key_id: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_get_pubkey_ext(device: ATCADevice, key_id: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_hmac(mode: u8, key_id: u16, digest: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_info_base(mode: u8, param2: u16, out_data: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_info(revision: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_info_ext(device: ATCADevice, revision: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_info_lock_status(param2: u16, is_locked: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_info_chip_status(chip_status: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_info_set_latch(state: bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_info_get_latch(state: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_kdf(
        mode: u8,
        key_id: u16,
        details: u32,
        message: *const u8,
        out_data: *mut u8,
        out_nonce: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock(mode: u8, summary_crc: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock_config_zone() -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock_config_zone_ext(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock_config_zone_crc(summary_crc: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock_data_zone() -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock_data_zone_ext(device: ATCADevice) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock_data_zone_crc(summary_crc: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock_data_slot(slot: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_lock_data_slot_ext(device: ATCADevice, slot: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_mac(mode: u8, key_id: u16, challenge: *const u8, digest: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_nonce_base(mode: u8, zero: u16, num_in: *const u8, rand_out: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_nonce(num_in: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_nonce_load(target: u8, num_in: *const u8, num_in_size: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_nonce_rand(num_in: *const u8, rand_out: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_nonce_rand_ext(device: ATCADevice, num_in: *const u8, rand_out: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_challenge(num_in: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_challenge_seed_update(num_in: *const u8, rand_out: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_priv_write(
        key_id: u16,
        priv_key: *const [u8; 36usize],
        write_key_id: u16,
        write_key: *const [u8; 32usize],
        num_in: *const [u8; 20usize],
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_random(rand_out: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_random_ext(device: ATCADevice, rand_out: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_zone(zone: u8, slot: u16, block: u8, offset: u8, data: *mut u8, len: u8)
        -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_zone_ext(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        block: u8,
        offset: u8,
        data: *mut u8,
        len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_locked(zone: u8, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_config_locked(is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_config_locked_ext(device: ATCADevice, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_data_locked(is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_data_locked_ext(device: ATCADevice, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_slot_locked(slot: u16, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_slot_locked_ext(device: ATCADevice, slot: u16, is_locked: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_private_ext(device: ATCADevice, slot: u16, is_private: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_is_private(slot: u16, is_private: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_bytes_zone_ext(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        offset: usize,
        data: *mut u8,
        length: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_bytes_zone(
        zone: u8,
        slot: u16,
        offset: usize,
        data: *mut u8,
        length: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_serial_number(serial_number: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_serial_number_ext(device: ATCADevice, serial_number: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_pubkey(slot: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_pubkey_ext(device: ATCADevice, slot: u16, public_key: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_sig(slot: u16, sig: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_config_zone(config_data: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_config_zone_ext(device: ATCADevice, config_data: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_cmp_config_zone(config_data: *mut u8, same_config: *mut bool) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_read_enc(
        key_id: u16,
        block: u8,
        data: *mut u8,
        enc_key: *const u8,
        enc_key_id: u16,
        num_in: *const [u8; 20usize],
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_secureboot(
        mode: u8,
        param2: u16,
        digest: *const u8,
        signature: *const u8,
        mac: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_secureboot_mac(
        mode: u8,
        digest: *const u8,
        signature: *const u8,
        num_in: *const u8,
        io_key: *const u8,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_selftest(mode: u8, param2: u16, result: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_base(
        mode: u8,
        length: u16,
        data_in: *const u8,
        data_out: *mut u8,
        data_out_size: *mut u16,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_start() -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_update(message: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_end(digest: *mut u8, length: u16, message: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_read_context(context: *mut u8, context_size: *mut u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_write_context(context: *const u8, context_size: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha(length: u16, message: *const u8, digest: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_hw_sha2_256(data: *const u8, data_size: usize, digest: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_hw_sha2_256_init(ctx: *mut atca_sha256_ctx_t) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_hw_sha2_256_update(
        ctx: *mut atca_sha256_ctx_t,
        data: *const u8,
        data_size: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_hw_sha2_256_finish(ctx: *mut atca_sha256_ctx_t, digest: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_hmac_init(ctx: *mut atca_hmac_sha256_ctx_t, key_slot: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_hmac_update(
        ctx: *mut atca_hmac_sha256_ctx_t,
        data: *const u8,
        data_size: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_hmac_finish(
        ctx: *mut atca_hmac_sha256_ctx_t,
        digest: *mut u8,
        target: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_hmac(
        data: *const u8,
        data_size: usize,
        key_slot: u16,
        digest: *mut u8,
        target: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sha_hmac_ext(
        device: ATCADevice,
        data: *const u8,
        data_size: usize,
        key_slot: u16,
        digest: *mut u8,
        target: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sign_base(mode: u8, key_id: u16, signature: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sign(key_id: u16, msg: *const u8, signature: *mut u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sign_ext(device: ATCADevice, key_id: u16, msg: *const u8, signature: *mut u8)
        -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_sign_internal(
        key_id: u16,
        is_invalidate: bool,
        is_full_sn: bool,
        signature: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_updateextra(mode: u8, new_value: u16) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify(
        mode: u8,
        key_id: u16,
        signature: *const u8,
        public_key: *const u8,
        other_data: *const u8,
        mac: *mut u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_extern(
        message: *const u8,
        signature: *const u8,
        public_key: *const u8,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_extern_ext(
        device: ATCADevice,
        message: *const u8,
        signature: *const u8,
        public_key: *const u8,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_extern_mac(
        message: *const u8,
        signature: *const u8,
        public_key: *const u8,
        num_in: *const u8,
        io_key: *const u8,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_stored(
        message: *const u8,
        signature: *const u8,
        key_id: u16,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_stored_ext(
        device: ATCADevice,
        message: *const u8,
        signature: *const u8,
        key_id: u16,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_stored_with_tempkey(
        signature: *const u8,
        key_id: u16,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_stored_mac(
        message: *const u8,
        signature: *const u8,
        key_id: u16,
        num_in: *const u8,
        io_key: *const u8,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_validate(
        key_id: u16,
        signature: *const u8,
        other_data: *const u8,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_verify_invalidate(
        key_id: u16,
        signature: *const u8,
        other_data: *const u8,
        is_verified: *mut bool,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write(zone: u8, address: u16, value: *const u8, mac: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_zone(
        zone: u8,
        slot: u16,
        block: u8,
        offset: u8,
        data: *const u8,
        len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_zone_ext(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        block: u8,
        offset: u8,
        data: *const u8,
        len: u8,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_bytes_zone_ext(
        device: ATCADevice,
        zone: u8,
        slot: u16,
        offset_bytes: usize,
        data: *const u8,
        length: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_bytes_zone(
        zone: u8,
        slot: u16,
        offset_bytes: usize,
        data: *const u8,
        length: usize,
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_pubkey(slot: u16, public_key: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_pubkey_ext(device: ATCADevice, slot: u16, public_key: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_config_zone(config_data: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_config_zone_ext(device: ATCADevice, config_data: *const u8) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_enc(
        key_id: u16,
        block: u8,
        data: *const u8,
        enc_key: *const u8,
        enc_key_id: u16,
        num_in: *const [u8; 20usize],
    ) -> ATCA_STATUS;
}
unsafe extern "C" {
    pub fn atcab_write_config_counter(counter_id: u16, counter_value: u32) -> ATCA_STATUS;
}
