// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

import { TR2, TrId } from "../../gen/tr.slint";
import { Palette, Size } from "@ui/theme.slint";
import { 
    MenuSectionContainer, 
    MenuActionItem, 
    HLine, MenuItemLayout, ItemTextPreview, MenuSectionLayout,
    BasePage,
    PageBody,
    ItemTextSm,
} from "@ui/widgets.slint";

import { SettingsProps } from "props.slint";
import { Navigate } from "../../gen/navigate.slint";
import { SettingsNavHeader } from "../../widgets/nav-header.slint";
import { SettingGlobal } from "../../globals/setting-global.slint";
import { BatteryGlobal } from "../../globals/battery-global.slint";

export component SettingsPage inherits BasePage {
    in property <SettingsProps> props;

    private property <int> battery-click-count;

    VerticalLayout {
        SettingsNavHeader {
            title: TR2.lookup(TrId.SettingsTitle);
        }

        PageBody {
            MenuSectionContainer {
                MenuSectionLayout {
                    MenuActionItem {
                        first: true;
                        label: TR2.lookup(TrId.SettingsDeviceName);
                        text: SettingGlobal.device-name;
                        clicked => {
                            Navigate.device-name({ });
                        }
                    }

                    HLine { }

                    MenuActionItem {
                        label: "Date & Time";
                        clicked => {
                            Navigate.date-time({ });
                        }
                    }

                    HLine { }

                    MenuActionItem {
                        label: "Display";
                        clicked => {
                            Navigate.display({ });
                        }
                    }

                    HLine { }

                    MenuActionItem {
                        // fix
                        // label: TR2.lookup(TrId.SettingsAutoLock);
                        label: "Auto Lock";
                        text: SettingGlobal.format-auto-lock(SettingGlobal.auto-lock);
                        clicked => {
                            Navigate.auto-lock({ });
                        }
                    }

                    HLine { }

                    MenuItemLayout {
                        label: TR2.lookup(TrId.SettingsBattery);

                        ItemTextSm {
                            text: BatteryGlobal.battery-level + "%";
                            color: Palette.content-tertiary;
                        }

                        clicked => {
                            if (battery-click-count > 3) {
                                battery-click-count = 0;
                                Navigate.battery({ });
                            } else {
                                battery-click-count += 1;
                            }
                        }
                    }

                    HLine { }

                    MenuActionItem {
                        label: TR2.lookup(TrId.SettingsSecurity);
                        clicked => {
                            Navigate.security({ });
                        }
                    }

                    HLine { }

                    MenuActionItem {
                        label: TR2.lookup(TrId.SettingsAdvancedMenu);
                        clicked => {
                            Navigate.advanced({ });
                        }
                    }

                    HLine { }

                    MenuActionItem {
                        last: true;
                        label: TR2.lookup(TrId.SettingsAbout);
                        clicked => {
                            Navigate.about({ });
                        }
                    }
                }
            }
        }
    }
}
