// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

export global AppCrashedGlobal { }

export global GenericAlertGlobal {
    in property <string> app-title: "";
    in property <string> title: "";
    in property <string> icon: "alert";
    in property <string> line1: "";
    in property <string> line2: "";

    in property <string> button1-title: "";
    in property <string> button2-title: "";
    in property <string> button3-title: "";
}
