// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

import { IconButton, Panel, HeadingMd, TextSm, Qrcode } from "@ui/widgets.slint";
import { Palette, Size } from "@ui/theme.slint";
import { TR2, TrId } from "../gen/tr.slint";


component QRCodePanel inherits Panel {
    in-out property <string> url;

    level: 4;
    padding: Size.sz6;

    width: 400px;
    TouchArea {
        // prevent clicks from reaching the overlay
    }

    VerticalLayout {
        padding: Size.sz6;
        spacing: Size.sz2;

        HorizontalLayout {
            alignment: end;

            VerticalLayout {
                IconButton {
                    icon: "close";
                    size: Size.sz6;
                    touch-factor: 4;

                    clicked => {
                        root.url = "";
                    }
                }
            }
        }

        VerticalLayout {
            spacing: Size.sz8;

            VerticalLayout {
                spacing: Size.sz4;

                HeadingMd {
                    text: TR2.lookup(TrId.SupportModalDocumentationHeader);
                    color: Palette.content-primary;
                    horizontal-alignment: center;
                }

                TextSm {
                    text: root.url;
                    color: Palette.content-primary;
                    horizontal-alignment: center;
                }
            }

            HorizontalLayout {
                alignment: center;

                Qrcode {
                    width: 351px;
                    height: 351px;
                    data: root.url;
                }
            }
        }
    }
}

export component QrOverlay inherits Rectangle {
    background: Palette.overlay;

    in-out property <string> url;

    TouchArea {
        clicked => {
            url = "";
        }
    }

    if url != "": QRCodePanel {
        url <=> root.url;
    }
}
