// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Router } from "gen/router.slint";
import { Size, Images, CurrentTheme, Palettes, Utils, UISize, Timings } from "@ui/theme.slint";
import { Callbacks } from "callbacks.slint";
import { TR } from "@ui/i18n/i18n.slint";
import { BaseWindow } from "@ui/widgets.slint"; 

import { AboutGlobal } from "./globals/about-global.slint";
import { BackupGlobal } from "./globals/backup-global.slint";
import { BatteryGlobal } from "./globals/battery-global.slint";
import { DateTimeGlobal } from "./globals/date-time-global.slint";
import { KeycardBackupGlobal } from "./globals/keycard-backup-global.slint";
import { LogGlobal } from "./globals/log-global.slint";
import { PinGlobal } from "./globals/pin-global.slint";
import { QlGlobal } from "./globals/ql-global.slint"; 
import { SettingGlobal } from "./globals/setting-global.slint";
import { UpdateGlobal } from "./globals/update-global.slint";
import { VerifyKeycardBackupGlobal } from "./globals/verify-keycard-global.slint";
import { SaveSettingsGlobal } from "./globals/save-settings-global.slint";

export {
    AboutGlobal,
    BackupGlobal,
    BatteryGlobal,
    DateTimeGlobal,
    KeycardBackupGlobal,
    LogGlobal,
    PinGlobal,
    QlGlobal,
    SettingGlobal,
    UpdateGlobal,
    VerifyKeycardBackupGlobal,
    SaveSettingsGlobal,
}


export component AppWindow inherits BaseWindow {
    Router { }
}

export * from "gen/exports.slint";
export { Callbacks }
export { CurrentTheme, Images, TR, Utils }
