// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import {Page} from "./page.slint";
import {HeadingLg} from "@ui/widgets.slint";
import {Utils, Size, Images} from "@ui/theme.slint";

export component SvgPage inherits Page {

    VerticalLayout {
        alignment: start;
        spacing: Size.sz6;
        HeadingLg {
            text: "Ghostscript Tiger!";
            height: 50px;
        }

        HorizontalLayout {
            spacing: Size.sz6;
            Image {
                source: Images.common("images/tiger");
            }
        }
    }
}
