// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

// Global colors used in all palettes

export global UIColors {
    // Primary
    out property <brush> primary-white: #ffffff;
    out property <brush> primary-black: #000000;
    out property <brush> transparent: #ffffff00;

    // Neutral
    out property <brush> neutral-950: #231f20;
    out property <brush> neutral-900: #454444;
    out property <brush> neutral-800: #5a595a;
    out property <brush> neutral-700: #747374;
    out property <brush> neutral-600: #959394;
    out property <brush> neutral-500: #a4a2a3;
    out property <brush> neutral-400: #b6b5b5;
    out property <brush> neutral-300: #c2c1c1;
    out property <brush> neutral-200: #d5d4d5;
    out property <brush> neutral-100: #e3e2e2;
    out property <brush> neutral-75: #ebebeb;
    out property <brush> neutral-50: #f6f6f6;

    // Dark Copper
    out property <brush> dark-copper-900: #503128;
    out property <brush> dark-copper-800: #694034;
    out property <brush> dark-copper-700: #885343;
    out property <brush> dark-copper-600: #ae6a56;
    out property <brush> dark-copper-500: #bf755f;
    out property <brush> dark-copper-400: #cc917f;
    out property <brush> dark-copper-300: #d4a394;
    out property <brush> dark-copper-200: #e2c0b5;
    out property <brush> dark-copper-100: #ebd4cd;
    out property <brush> dark-copper-50: #fbf3f1;

    // Light Copper
    out property <brush> light-copper-900: #523a2e;
    out property <brush> light-copper-800: #764c3d;
    out property <brush> light-copper-700: #98634e;
    out property <brush> light-copper-600: #c37e64;
    out property <brush> light-copper-500: #d68b6e;
    out property <brush> light-copper-400: #dea28b;
    out property <brush> light-copper-300: #e4b19e;
    out property <brush> light-copper-200: #eccabc;
    out property <brush> light-copper-100: #f2dbd2;
    out property <brush> light-copper-50: #fbf3f1;

    // Bronze
    out property <brush> bronze-900: #30221d;
    out property <brush> bronze-800: #3f2c26;
    out property <brush> bronze-700: #523931;
    out property <brush> bronze-600: #69493f;
    out property <brush> bronze-500: #735045;
    out property <brush> bronze-400: #8f736a;
    out property <brush> bronze-300: #a18a82;
    out property <brush> bronze-200: #bfafa9;
    out property <brush> bronze-100: #d4c9c5;
    out property <brush> bronze-50: #f1eeec;

    // blue
    out property <brush> blue-900: #00424e;
    out property <brush> blue-800: #005666;
    out property <brush> blue-700: #006f83;
    out property <brush> blue-600: #008fa8;
    out property <brush> blue-500: #009db9;
    out property <brush> blue-400: #33b1c7;
    out property <brush> blue-300: #54bdd0;
    out property <brush> blue-200: #8ad2df;
    out property <brush> blue-100: #b0e1e9;
    out property <brush> blue-50: #e6f5f8;

    // teal
    out property <brush> teal-900: #00454b;
    out property <brush> teal-800: #005b62;
    out property <brush> teal-700: #00757e;
    out property <brush> teal-600: #0096a2;
    out property <brush> teal-500: #00a5b2;
    out property <brush> teal-400: #33b7c1;
    out property <brush> teal-300: #54c3cb;
    out property <brush> teal-200: #8ad6dc;
    out property <brush> teal-100: #b0e3e7;
    out property <brush> teal-50: #e6f6f7;

    // pine
    out property <brush> pine-900: #003333;
    out property <brush> pine-800: #004343;
    out property <brush> pine-700: #005757;
    out property <brush> pine-600: #006f6f;
    out property <brush> pine-500: #007a7a;
    out property <brush> pine-400: #339595;
    out property <brush> pine-300: #54a6a6;
    out property <brush> pine-200: #8ac2c2;
    out property <brush> pine-100: #b0d6d6;
    out property <brush> pine-50: #e6f2f2;

    // green
    out property <brush> green-900: #133e37;
    out property <brush> green-800: #195148;
    out property <brush> green-700: #21695d;
    out property <brush> green-600: #2a8777;
    out property <brush> green-500: #2e9483;
    out property <brush> green-400: #58a99c;
    out property <brush> green-300: #73b7ac;
    out property <brush> green-200: #9fcec6;
    out property <brush> green-100: #beded9;
    out property <brush> green-50: #eaf4f3;

    // purple
    out property <brush> purple-900: #42256b;
    out property <brush> purple-800: #57308c;
    out property <brush> purple-700: #703eb5;
    out property <brush> purple-600: #904fe8;
    out property <brush> purple-500: #9e57ff;
    out property <brush> purple-400: #b179ff;
    out property <brush> purple-300: #be8eff;
    out property <brush> purple-200: #d2b2ff;
    out property <brush> purple-100: #e1cbff;
    out property <brush> purple-50: #f5eeff;

    // red
    out property <brush> red-900: #6b1515;
    out property <brush> red-800: #8c1c1c;
    out property <brush> red-700: #b52424;
    out property <brush> red-600: #e82e2e;
    out property <brush> red-500: #ff3333;
    out property <brush> red-400: #ff5c5c;
    out property <brush> red-300: #ff7676;
    out property <brush> red-200: #ffa1a1;
    out property <brush> red-100: #ffc0c0;
    out property <brush> red-50: #ffebeb;

    // orange
    out property <brush> orange-600: #e18618;
    out property <brush> orange-500: #f7931a;
    out property <brush> orange-200: #fbcd96;
}

export global UIGradients {
    out property <brush> switch-indeterminate: @linear-gradient(90deg, UIColors.teal-400 0%, UIColors.blue-500 100%);
    out property <brush> copper: @linear-gradient(90deg, UIColors.dark-copper-500 0%, UIColors.dark-copper-400 100%);
    // TBD: Add more gradients
}
