// SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Router } from "gen/router.slint";
import { Size, Images, CurrentTheme, Palettes, Utils, UISize } from "@ui/theme.slint";
import { Callbacks } from "callbacks.slint";
import { BaseWindow } from "@ui/widgets.slint";

export component AppWindow inherits BaseWindow {
    Router { }
}

export * from "gen/exports.slint";
export { Callbacks, CurrentTheme, Images, Utils }
