// SPDX-FileCopyrightText: 2025 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: MIT OR Apache-2.0

import { KeyView, EditCaller } from "../../security-key-types.slint";

import { CallbackResult } from "@ui/theme.slint";
export { CallbackResult }

import { EditPageVersion } from "@ui/pages.slint";
export { EditPageVersion }

@rust-attr(route(path = "/edit?{caller}&{key}&{version}"))
export struct EditProps {
    caller: EditCaller,
    key: KeyView,
    version: EditPageVersion,
}
