// SPDX-FileCopyrightText: 2023 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { CurrentTheme, Images, Utils } from "@ui/theme.slint";
import { Router } from "gen/router.slint";
import { Settings } from "settings.slint";
import { TR } from "@ui/i18n/i18n.slint";
import { Callbacks } from "callbacks.slint";
import { VerifyAddress } from "verify-address.slint";
import { CreateAccount } from "create-account.slint";
import { SignPsbt } from "sign-psbt.slint";
import { SignMessage } from "sign-message.slint";
import { BaseWindow } from "@ui/widgets.slint";
import { ExportAccount } from "export-account.slint";
import { EnterPassphrase } from "enter-passphrase.slint";

export { Utils, Images, CurrentTheme, Callbacks, Settings, VerifyAddress, CreateAccount, SignPsbt, SignMessage, ExportAccount, EnterPassphrase }
export { TR }
export * from "gen/exports.slint";

export component AppWindow inherits BaseWindow {
    Router { }
}
