use slint_keyos_platform::slint::ComponentHandle;
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Shared application state, held in a StoredValue<AppState> and threaded to
// every feature module (same ownership model as the Bitcoin app's AppState).

use secp256k1::Secp256k1;
use slint_keyos_platform::slint::Weak;

use crate::sign_tx::Origin;

// `AppWindow` is generated by the Slint build from ui/app.slint.
use crate::AppWindow;

pub struct AppState {
    ui: Weak<AppWindow>,
    /// One reusable secp256k1 context (signing + verification). Construction is
    /// expensive; build once and share.
    pub secp: Secp256k1<secp256k1::All>,
    /// Handle to the secure element / settings surface. `Security::default()`
    /// is the same constructor the Bitcoin app uses.
    pub security: crate::Security,
    /// Default account index the UI is currently operating on (m/44'/42'/N').
    pub account: u32,
    /// The decoded-but-not-yet-signed package awaiting user approval, with the
    /// transport it arrived on. Raw CBOR bytes are kept (not the parsed struct)
    /// so the parse is re-validated at sign time.
    pending: Option<(Origin, Vec<u8>)>,
    /// Animated-QR parts (UR frames) for the most recently signed tx, read back
    /// by the DynamicQrCode via the `signed-qr-parts` callback.
    signed_parts: Vec<String>,
}

impl AppState {
    pub fn new(ui: Weak<AppWindow>) -> Self {
        AppState {
            ui,
            secp: Secp256k1::new(),
            security: crate::Security::default(),
            account: 0,
            pending: None,
            signed_parts: Vec::new(),
        }
    }

    /// Upgrade the weak UI handle. Panics only if called after the window is
    /// gone, which cannot happen while a callback is running.
    pub fn ui(&self) -> AppWindow {
        self.ui.upgrade().expect("UI alive")
    }

    /// Stash a pending signing request (set at QR/SD ingest, cleared on sign).
    pub fn set_pending(&mut self, origin: Origin, bytes: Vec<u8>) {
        self.pending = Some((origin, bytes));
    }

    /// Clone out the pending request for the approval step.
    pub fn pending(&self) -> Option<(Origin, Vec<u8>)> {
        self.pending.clone()
    }

    /// Drop any pending request (Reject / Cancel).
    pub fn clear_pending(&mut self) {
        self.pending = None;
    }

    /// Store the animated-QR parts for the signed tx.
    pub fn set_signed_parts(&mut self, parts: Vec<String>) {
        self.signed_parts = parts;
    }

    /// Read the signed-tx QR parts (empty until a tx is signed).
    pub fn signed_qr_parts(&self) -> Vec<String> {
        self.signed_parts.clone()
    }
}
